package activitylog

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"aulyc.local/aulycmail/internal/database"
	"github.com/google/uuid"
)

var (
	ErrTypeRequired    = errors.New("activity log type is required")
	ErrInvalidStatus   = errors.New("invalid activity log status")
	ErrTitleRequired   = errors.New("activity log title is required")
	ErrSummaryRequired = errors.New("activity log summary is required")
)

// Store persists and queries activity records.
type Store struct {
	db  *database.DB
	now func() time.Time
}

func NewStore(db *database.DB) *Store {
	return &Store{db: db, now: time.Now}
}

// Append inserts an entry and applies the retention policy. Missing IDs and
// timestamps are generated by the store. The resulting values are written back
// to entry so callers can emit the canonical persisted record.
func (s *Store) Append(entry *Entry) error {
	if entry == nil {
		return errors.New("activity log entry is nil")
	}
	if err := validateEntry(*entry); err != nil {
		return err
	}

	now := s.now().UTC()
	if entry.ID == "" {
		entry.ID = uuid.NewString()
	}
	if entry.CreatedAt == "" {
		entry.CreatedAt = now.Format(time.RFC3339Nano)
	} else {
		createdAt, err := time.Parse(time.RFC3339Nano, entry.CreatedAt)
		if err != nil {
			return fmt.Errorf("invalid activity log createdAt: %w", err)
		}
		entry.CreatedAt = createdAt.UTC().Format(time.RFC3339Nano)
	}
	if entry.Payload == nil {
		entry.Payload = map[string]any{}
	}
	payloadJSON, err := json.Marshal(entry.Payload)
	if err != nil {
		return fmt.Errorf("marshal activity log payload: %w", err)
	}

	tx, err := s.db.Begin()
	if err != nil {
		return fmt.Errorf("begin activity log append: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	if _, err := tx.Exec(`
		INSERT INTO activity_logs
			(id, created_at, type, status, title, summary, detail, payload_json)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)
	`, entry.ID, entry.CreatedAt, entry.Type, entry.Status, entry.Title, entry.Summary,
		nullableString(entry.Detail), string(payloadJSON)); err != nil {
		return fmt.Errorf("insert activity log: %w", err)
	}
	if err := pruneWithExecutor(tx, now); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit activity log append: %w", err)
	}
	return nil
}

// List returns records ordered newest first, along with the total before
// pagination.
func (s *Store) List(query Query) (Page, error) {
	where, args, err := buildWhere(query)
	if err != nil {
		return Page{}, err
	}
	limit := query.Limit
	if limit <= 0 {
		limit = DefaultPageSize
	}
	if limit > MaxPageSize {
		limit = MaxPageSize
	}
	offset := query.Offset
	if offset < 0 {
		offset = 0
	}

	var total int
	if err := s.db.QueryRow("SELECT COUNT(*) FROM activity_logs"+where, args...).Scan(&total); err != nil {
		return Page{}, fmt.Errorf("count activity logs: %w", err)
	}

	listArgs := append(append([]any{}, args...), limit, offset)
	rows, err := s.db.Query(`
		SELECT id, created_at, type, status, title, summary, detail, payload_json
		FROM activity_logs`+where+`
		ORDER BY created_at DESC, id DESC
		LIMIT ? OFFSET ?
	`, listArgs...)
	if err != nil {
		return Page{}, fmt.Errorf("list activity logs: %w", err)
	}
	defer rows.Close()

	entries := make([]Entry, 0, limit)
	for rows.Next() {
		entry, err := scanEntry(rows)
		if err != nil {
			return Page{}, err
		}
		entries = append(entries, entry)
	}
	if err := rows.Err(); err != nil {
		return Page{}, fmt.Errorf("iterate activity logs: %w", err)
	}
	return Page{Entries: entries, Total: total}, nil
}

// Latest returns the newest matching record, or nil when no record exists.
func (s *Store) Latest(logType, directory string) (*Entry, error) {
	query := Query{Type: logType, Directory: directory, Limit: 1}
	page, err := s.List(query)
	if err != nil {
		return nil, err
	}
	if len(page.Entries) == 0 {
		return nil, nil
	}
	return &page.Entries[0], nil
}

// Clear deletes every record matching query filters. Pagination fields are
// intentionally ignored.
func (s *Store) Clear(query Query) (int64, error) {
	where, args, err := buildWhere(query)
	if err != nil {
		return 0, err
	}
	result, err := s.db.Exec("DELETE FROM activity_logs"+where, args...)
	if err != nil {
		return 0, fmt.Errorf("clear activity logs: %w", err)
	}
	count, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("count cleared activity logs: %w", err)
	}
	return count, nil
}

// Prune removes entries older than 30 days and then caps the remaining set at
// the newest 1000 records.
func (s *Store) Prune() error {
	tx, err := s.db.Begin()
	if err != nil {
		return fmt.Errorf("begin activity log prune: %w", err)
	}
	defer func() { _ = tx.Rollback() }()
	if err := pruneWithExecutor(tx, s.now().UTC()); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit activity log prune: %w", err)
	}
	return nil
}

type sqlExecutor interface {
	Exec(query string, args ...any) (sql.Result, error)
}

func pruneWithExecutor(exec sqlExecutor, now time.Time) error {
	cutoff := now.Add(-RetentionPeriod).Format(time.RFC3339Nano)
	if _, err := exec.Exec("DELETE FROM activity_logs WHERE created_at < ?", cutoff); err != nil {
		return fmt.Errorf("prune expired activity logs: %w", err)
	}
	if _, err := exec.Exec(`
		DELETE FROM activity_logs
		WHERE id IN (
			SELECT id FROM activity_logs
			ORDER BY created_at DESC, id DESC
			LIMIT -1 OFFSET ?
		)
	`, MaxEntries); err != nil {
		return fmt.Errorf("cap activity logs: %w", err)
	}
	return nil
}

func validateEntry(entry Entry) error {
	if strings.TrimSpace(entry.Type) == "" {
		return ErrTypeRequired
	}
	switch entry.Status {
	case StatusSuccess, StatusPartial, StatusFailed, StatusCancelled:
	default:
		return ErrInvalidStatus
	}
	if strings.TrimSpace(entry.Title) == "" {
		return ErrTitleRequired
	}
	if strings.TrimSpace(entry.Summary) == "" {
		return ErrSummaryRequired
	}
	return nil
}

func buildWhere(query Query) (string, []any, error) {
	clauses := make([]string, 0, 4)
	args := make([]any, 0, 4)
	if query.Type != "" {
		clauses = append(clauses, "type = ?")
		args = append(args, query.Type)
	}
	if query.ProblemOnly {
		clauses = append(clauses, "status IN (?, ?)")
		args = append(args, StatusPartial, StatusFailed)
	}
	if query.Date != "" {
		location := time.FixedZone("activity-log-client", -query.TimezoneOffsetMinutes*60)
		start, err := time.ParseInLocation("2006-01-02", query.Date, location)
		if err != nil {
			return "", nil, fmt.Errorf("invalid activity log date: %w", err)
		}
		clauses = append(clauses, "created_at >= ? AND created_at < ?")
		args = append(args,
			start.UTC().Format(time.RFC3339Nano),
			start.AddDate(0, 0, 1).UTC().Format(time.RFC3339Nano),
		)
	}
	if query.Directory != "" {
		clauses = append(clauses, "json_extract(payload_json, '$.directory') = ?")
		args = append(args, query.Directory)
	}
	if len(clauses) == 0 {
		return "", args, nil
	}
	return " WHERE " + strings.Join(clauses, " AND "), args, nil
}

type rowScanner interface {
	Scan(dest ...any) error
}

func scanEntry(row rowScanner) (Entry, error) {
	var entry Entry
	var detail sql.NullString
	var payloadJSON string
	if err := row.Scan(&entry.ID, &entry.CreatedAt, &entry.Type, &entry.Status,
		&entry.Title, &entry.Summary, &detail, &payloadJSON); err != nil {
		return Entry{}, fmt.Errorf("scan activity log: %w", err)
	}
	if detail.Valid {
		entry.Detail = detail.String
	}
	entry.Payload = map[string]any{}
	if err := json.Unmarshal([]byte(payloadJSON), &entry.Payload); err != nil {
		return Entry{}, fmt.Errorf("decode activity log payload: %w", err)
	}
	return entry, nil
}

func nullableString(value string) any {
	if value == "" {
		return nil
	}
	return value
}
