// @ts-ignore - generated by Wails
import { CheckForUpdates, GetUpdateStatus, InstallAvailableUpdate } from '../../../wailsjs/go/app/App.js'
import type { updater } from '../../../wailsjs/go/models'
import { EventsOn } from '../../../wailsjs/runtime/runtime.js'

class UpdateStore {
  status = $state<updater.Status>({
    state: 'idle',
    currentVersion: '',
    currentBuildNumber: 0,
    canInstall: false,
  } as updater.Status)
  private started = false

  start(): void {
    if (this.started) return
    this.started = true
    try {
      EventsOn('update:state', (status: updater.Status) => {
        if (status?.state) this.status = status
      })
    } catch {
      // Component tests and the browser-only preview do not provide Wails'
      // native event runtime. The packaged app always does.
    }
    void Promise.resolve()
      .then(() => GetUpdateStatus())
      .then((status) => {
        if (status?.state) this.status = status
      })
      .catch(() => {})
  }

  async check(): Promise<void> {
    this.status = await CheckForUpdates()
  }

  async install(): Promise<void> {
    this.status = await InstallAvailableUpdate()
  }
}

export const updateStore = new UpdateStore()
