<script lang="ts">
  import BackupDirectoryPicker from '$lib/components/backup/BackupDirectoryPicker.svelte'
  import { addToast } from '$lib/stores/toast'
  import { _ } from '$lib/i18n'
  // @ts-ignore - generated by Wails
  import { OpenBackupDirectory } from '../../../../../wailsjs/go/app/App.js'
  import type { SettingsDraft } from '../settingsDraft.svelte'
  import SettingsSection from '../shared/SettingsSection.svelte'
  import SettingsRow from '../shared/SettingsRow.svelte'
  import BackupScopePicker from './BackupScopePicker.svelte'
  interface Props { draft: SettingsDraft; running?: boolean }
  let { draft, running = false }: Props = $props()

  function setDirectory(path: string) {
    draft.backupDirectory = path.trim()
  }
  async function openDirectory() {
    try { await OpenBackupDirectory(draft.backupDirectory) }
    catch { addToast({ type: 'error', message: $_('settingsBackup.openDirectoryFailed') }) }
  }
</script>

<SettingsSection framed={false}>
  <SettingsRow label={$_('settingsBackup.directory')}>
    <div class="w-[32rem] max-w-full"><BackupDirectoryPicker directory={draft.backupDirectory} placeholder={$_('settingsBackup.directoryPlaceholder')} disabled={running} openDisabled={draft.backupDirty} onChoose={setDirectory} onSelectHistory={setDirectory} onOpenDirectory={openDirectory} onChooseError={() => addToast({ type: 'error', message: $_('settingsBackup.chooseDirectoryFailed') })} /></div>
  </SettingsRow>
  <SettingsRow label={$_('settingsBackup.scope')}>
    <BackupScopePicker bind:scope={draft.backupScope} bind:selectedAccountIds={draft.backupSelectedAccountIds} disabled={running} />
  </SettingsRow>
</SettingsSection>
