import { EventsOn } from '../../../../../wailsjs/runtime/runtime'
// @ts-ignore - generated by Wails
import { GetBackupRunState, StartEmailBackup } from '../../../../../wailsjs/go/app/App.js'
import type { BackupScope } from '../settingsDraft.svelte'

export interface BackupProgress {
  phase: string
  accountEmail?: string
  folderPath?: string
  current: number
  total: number
  exported: number
  skipped: number
  missing?: number
  unavailable?: number
  failed: number
  message?: string
}

export class BackupRunStore {
  running = $state(false)
  loading = $state(false)
  progress = $state<BackupProgress | null>(null)
  private unsubscribe?: () => void

  async startListening(): Promise<void> {
    this.unsubscribe ??= EventsOn('backup:progress', (progress: BackupProgress) => {
      this.progress = progress
      this.running = progress.phase === 'running'
    })
    await this.refresh()
  }

  stopListening(): void { this.unsubscribe?.(); this.unsubscribe = undefined }

  async refresh(): Promise<void> {
    const state = await GetBackupRunState()
    this.running = Boolean(state?.running)
    this.progress = state?.progress ?? null
  }

  async start(directory: string, scope: BackupScope, selectedAccountIds: string[]): Promise<void> {
    this.loading = true
    this.running = true
    this.progress = { phase: 'running', current: 0, total: 0, exported: 0, skipped: 0, missing: 0, unavailable: 0, failed: 0 }
    try {
      const state = await StartEmailBackup({ directory, scope, selectedAccountIds })
      this.running = Boolean(state?.running)
      this.progress = state?.progress ?? this.progress
    } finally {
      this.loading = false
      await this.refresh()
    }
  }
}
