<script lang="ts">
  import { onDestroy } from 'svelte'
  import Icon from '@iconify/svelte'
  import { _ } from '$lib/i18n'
  import { EventsOn } from '../../../../../wailsjs/runtime/runtime'
  // @ts-ignore - generated by Wails
  import { GetBackupStatus, GetLatestActivityLog } from '../../../../../wailsjs/go/app/App.js'
  import type { ActivityLog } from '../activity/activityLogTypes'
  import { activitySummary, activityTime } from '../activity/activityLogFormat'
  import SettingsSection from '../shared/SettingsSection.svelte'
  interface Props { directory: string }
  let { directory }: Props = $props()
  let log = $state<ActivityLog | null>(null)
  let hasIndex = $state(false)
  let loading = $state(false)
  let loadFailed = $state(false)
  let loadedDirectory = ''

  async function refresh(path: string) {
    loadedDirectory = path
    if (!path) { log = null; hasIndex = false; loadFailed = false; loading = false; return }
    loading = true
    loadFailed = false
    try {
      const [latest, status] = await Promise.all([GetLatestActivityLog('backup', path), GetBackupStatus(path)])
      if (loadedDirectory !== path) return
      log = latest ?? null
      hasIndex = Boolean(status?.hasIndex)
    } catch (error) {
      console.error('Failed to load latest backup log:', error)
      if (loadedDirectory === path) { log = null; hasIndex = false; loadFailed = true }
    } finally { if (loadedDirectory === path) loading = false }
  }
  $effect(() => { void refresh(directory.trim()) })
  const unsubscribe = EventsOn('activity-log:created', (event: ActivityLog) => { if (event?.type === 'backup') void refresh(directory.trim()) })
  onDestroy(unsubscribe)
</script>

<SettingsSection title={$_('settingsBackup.recentLog')}>
  <div class="min-h-16 px-4 py-3 text-sm">
    {#if loading}<Icon icon="mdi:loading" class="h-5 w-5 animate-spin text-muted-foreground" />
    {:else if log}<p>{activityTime(log.createdAt)} · {activitySummary(log)}</p>
    {:else if loadFailed}<p class="text-destructive">{$_('activityLog.loadFailed')}</p>
    {:else if hasIndex}<p class="text-muted-foreground">{$_('settingsBackup.indexWithoutLog')}</p>
    {:else}<p class="text-muted-foreground">{$_('settingsBackup.noRecentLog')}</p>{/if}
  </div>
</SettingsSection>
