<script lang="ts">
  import { onDestroy } from 'svelte'
  import Icon from '@iconify/svelte'
  import { _ } from '$lib/i18n'
  import { EventsOn } from '../../../../../wailsjs/runtime/runtime'
  // @ts-ignore - generated by Wails
  import { GetBackupStatus, GetLatestActivityLog } from '../../../../../wailsjs/go/app/App.js'
  import type { ActivityLog } from '../activity/activityLogTypes'
  import { activitySummary, activityTime } from '../activity/activityLogFormat'
  interface Props { directory: string }
  let { directory }: Props = $props()
  let log = $state<ActivityLog | null>(null)
  let hasIndex = $state(false)
  let loading = $state(false)
  let loadFailed = $state(false)
  let loadedDirectory = ''

  async function refresh(path: string) {
    loadedDirectory = path
    if (!path) { log = null; hasIndex = false; loadFailed = false; loading = false; return }
    loading = true
    loadFailed = false
    try {
      const [latest, status] = await Promise.all([GetLatestActivityLog('backup', path), GetBackupStatus(path)])
      if (loadedDirectory !== path) return
      log = latest ?? null
      hasIndex = Boolean(status?.hasIndex)
    } catch (error) {
      console.error('Failed to load latest backup log:', error)
      if (loadedDirectory === path) { log = null; hasIndex = false; loadFailed = true }
    } finally { if (loadedDirectory === path) loading = false }
  }
  $effect(() => { void refresh(directory.trim()) })
  const unsubscribe = EventsOn('activity-log:created', (event: ActivityLog) => { if (event?.type === 'backup') void refresh(directory.trim()) })
  onDestroy(unsubscribe)
</script>

<section class="border-b border-border/75">
  <div class="flex min-h-14 items-center gap-4 py-1.5 text-sm">
    <h3 class="shrink-0 font-semibold text-foreground">{$_('settingsBackup.recentLog')}</h3>
    <div class="ml-auto min-w-0 flex-1 text-right">
      {#if loading}<Icon icon="mdi:loading" class="h-5 w-5 animate-spin text-muted-foreground" />
      {:else if log}
        {@const summaryParts = activitySummary(log).split(' · ')}
        <div class="flex flex-wrap justify-end gap-x-3 gap-y-1">
          <span>{activityTime(log.createdAt)}</span>
          {#if summaryParts[0]}<span>{summaryParts[0]}</span>{/if}
        </div>
        {#if summaryParts.length > 1}
          <div class="mt-1 flex flex-wrap justify-end gap-x-3 gap-y-1 text-muted-foreground">
            {#each summaryParts.slice(1) as part (part)}<span>{part}</span>{/each}
          </div>
        {/if}
      {:else if loadFailed}<span class="text-destructive">{$_('activityLog.loadFailed')}</span>
      {:else if hasIndex}<span class="text-muted-foreground">{$_('settingsBackup.indexWithoutLog')}</span>
      {:else}<span class="text-muted-foreground">{$_('settingsBackup.noRecentLog')}</span>{/if}
    </div>
  </div>
</section>
