<script lang="ts">
  import { onDestroy } from 'svelte'
  import Icon from '@iconify/svelte'
  import { _ } from '$lib/i18n'
  import { EventsOn } from '../../../../../wailsjs/runtime/runtime'
  // @ts-ignore - generated by Wails
  import { GetBackupStatus, GetLatestActivityLog } from '../../../../../wailsjs/go/app/App.js'
  import type { ActivityLog } from '../activity/activityLogTypes'
  import { activityStatusLabel, activityTime, backupActivityDetails } from '../activity/activityLogFormat'
  interface Props { directory: string; onOpenLogs?: () => void }
  let { directory, onOpenLogs }: Props = $props()
  let log = $state<ActivityLog | null>(null)
  let hasIndex = $state(false)
  let loading = $state(false)
  let loadFailed = $state(false)
  let loadedDirectory = ''

  async function refresh(path: string) {
    loadedDirectory = path
    if (!path) { log = null; hasIndex = false; loadFailed = false; loading = false; return }
    loading = true
    loadFailed = false
    try {
      const [latest, status] = await Promise.all([GetLatestActivityLog('backup', path), GetBackupStatus(path)])
      if (loadedDirectory !== path) return
      log = latest ?? null
      hasIndex = Boolean(status?.hasIndex)
    } catch (error) {
      console.error('Failed to load latest backup log:', error)
      if (loadedDirectory === path) { log = null; hasIndex = false; loadFailed = true }
    } finally { if (loadedDirectory === path) loading = false }
  }
  $effect(() => { void refresh(directory.trim()) })
  const unsubscribe = EventsOn('activity-log:created', (event: ActivityLog) => { if (event?.type === 'backup') void refresh(directory.trim()) })
  onDestroy(unsubscribe)
  const details = $derived(log ? backupActivityDetails(log) : null)
  const statusClass = $derived(log?.status === 'success'
    ? 'text-emerald-500'
    : log?.status === 'partial'
      ? 'text-amber-500'
      : log?.status === 'cancelled'
        ? 'text-muted-foreground'
        : 'text-destructive')
  const statusIcon = $derived(log?.status === 'success' ? 'mdi:check-circle' : log?.status === 'cancelled' ? 'mdi:cancel' : 'mdi:alert-circle')
  const summary = $derived.by(() => {
    if (!log) return ''
    if (log.status === 'success' && details) {
      return $_('settingsBackup.recentSuccess', { values: { count: details.statistics.newlyBackedUp } })
    }
    if (log.status === 'partial' && details) {
      return $_('settingsBackup.recentPartial', { values: { count: details.statistics.notBackedUp } })
    }
    return activityStatusLabel(log.status)
  })
</script>

<section class="border-b border-border/75">
  <div class="flex min-h-14 items-center gap-4 py-1.5 text-sm">
    <h3 class="shrink-0 font-semibold text-foreground">{$_('settingsBackup.recentLog')}</h3>
    <div class="ml-auto flex min-w-0 flex-1 items-center justify-end gap-3 text-xs">
      {#if loading}<Icon icon="mdi:loading" class="h-5 w-5 animate-spin text-muted-foreground" />
      {:else if log}
        <Icon icon={statusIcon} class={`h-4 w-4 shrink-0 ${statusClass}`} />
        <span class="min-w-0 truncate text-foreground" title={summary}>{summary}</span>
        <time class="shrink-0 tabular-nums text-muted-foreground">{activityTime(log.createdAt)}</time>
        {#if onOpenLogs}
          <button type="button" class="flex shrink-0 items-center gap-0.5 font-medium text-primary hover:underline" onclick={onOpenLogs}>
            {$_('settingsBackup.viewLogs')}<Icon icon="mdi:chevron-right" class="h-4 w-4" />
          </button>
        {/if}
      {:else if loadFailed}<span class="text-destructive">{$_('activityLog.loadFailed')}</span>
      {:else if hasIndex}<span class="text-muted-foreground">{$_('settingsBackup.indexWithoutLog')}</span>
      {:else}<span class="text-muted-foreground">{$_('settingsBackup.noRecentLog')}</span>{/if}
    </div>
  </div>
</section>
