import { EventsOn } from '../../../../../wailsjs/runtime/runtime'
import { get } from 'svelte/store'
import { _ } from '$lib/i18n'
import { addToast } from '$lib/stores/toast'
// @ts-ignore - generated by Wails
import { ClearActivityLogs, ListActivityLogs } from '../../../../../wailsjs/go/app/App.js'
import type { ActivityLog, ActivityLogQuery } from './activityLogTypes'

const PAGE_SIZE = 50

export class ActivityLogsStore {
  entries = $state<ActivityLog[]>([])
  total = $state(0)
  loading = $state(false)
  clearing = $state(false)
  loadFailed = $state(false)
  type = $state('')
  problemOnly = $state(false)
  date = $state('')
  private unsubscribe?: () => void

  get hasMore(): boolean { return this.entries.length < this.total }

  start(): void {
    if (this.unsubscribe) return
    this.unsubscribe = EventsOn('activity-log:created', () => { void this.refresh() })
  }

  stop(): void {
    this.unsubscribe?.()
    this.unsubscribe = undefined
  }

  query(limit = PAGE_SIZE, offset = 0): ActivityLogQuery {
    return { type: this.type, problemOnly: this.problemOnly, date: this.date, timezoneOffsetMinutes: new Date().getTimezoneOffset(), directory: '', limit, offset }
  }

  async refresh(): Promise<void> {
    this.loading = true
    this.loadFailed = false
    try {
      const result = await ListActivityLogs(this.query())
      this.entries = result?.entries ?? []
      this.total = result?.total ?? 0
    } catch (error) {
      console.error('Failed to load activity logs:', error)
      this.loadFailed = true
    } finally {
      this.loading = false
    }
  }

  async loadMore(): Promise<void> {
    if (this.loading || !this.hasMore) return
    this.loading = true
    try {
      const result = await ListActivityLogs(this.query(PAGE_SIZE, this.entries.length))
      this.entries = [...this.entries, ...(result?.entries ?? [])]
      this.total = result?.total ?? this.total
    } catch (error) {
      console.error('Failed to load more activity logs:', error)
      addToast({ type: 'error', message: get(_)('activityLog.loadFailed') })
    } finally {
      this.loading = false
    }
  }

  async setFilter(type: string, problemOnly = false): Promise<void> {
    this.type = type
    this.problemOnly = problemOnly
    await this.refresh()
  }

  async clearCurrent(): Promise<void> {
    this.clearing = true
    try {
      await ClearActivityLogs(this.query(0, 0))
      await this.refresh()
    } catch (error) {
      console.error('Failed to clear filtered activity logs:', error)
      addToast({ type: 'error', message: get(_)('activityLog.clearFailed') })
    } finally {
      this.clearing = false
    }
  }

  async clearAll(): Promise<void> {
    this.clearing = true
    try {
      await ClearActivityLogs({ type: '', problemOnly: false, date: '', timezoneOffsetMinutes: new Date().getTimezoneOffset(), directory: '', limit: 0, offset: 0 })
      await this.refresh()
    } catch (error) {
      console.error('Failed to clear activity logs:', error)
      addToast({ type: 'error', message: get(_)('activityLog.clearFailed') })
    } finally {
      this.clearing = false
    }
  }
}
