// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptCertificate(arg1, arg2, arg3) {
  return window['go']['app']['App']['AcceptCertificate'](arg1, arg2, arg3);
}

export function AddAccount(arg1) {
  return window['go']['app']['App']['AddAccount'](arg1);
}

export function AddImageAllowlist(arg1, arg2) {
  return window['go']['app']['App']['AddImageAllowlist'](arg1, arg2);
}

export function Archive(arg1) {
  return window['go']['app']['App']['Archive'](arg1);
}

export function CancelAllSyncs() {
  return window['go']['app']['App']['CancelAllSyncs']();
}

export function CancelFolderSync(arg1, arg2) {
  return window['go']['app']['App']['CancelFolderSync'](arg1, arg2);
}

export function ChooseBackupDirectory() {
  return window['go']['app']['App']['ChooseBackupDirectory']();
}

export function Contacts_BrowseContacts(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Contacts_BrowseContacts'](arg1, arg2, arg3, arg4);
}

export function Contacts_CreateContact(arg1) {
  return window['go']['app']['App']['Contacts_CreateContact'](arg1);
}

export function Contacts_DeleteLocalContact(arg1) {
  return window['go']['app']['App']['Contacts_DeleteLocalContact'](arg1);
}

export function Contacts_GetContactAccountGroups() {
  return window['go']['app']['App']['Contacts_GetContactAccountGroups']();
}

export function Contacts_GetContactDetail(arg1) {
  return window['go']['app']['App']['Contacts_GetContactDetail'](arg1);
}

export function Contacts_ListContactsForBrowse(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Contacts_ListContactsForBrowse'](arg1, arg2, arg3, arg4);
}

export function Contacts_UpdateContact(arg1, arg2) {
  return window['go']['app']['App']['Contacts_UpdateContact'](arg1, arg2);
}

export function CopyToFolder(arg1, arg2) {
  return window['go']['app']['App']['CopyToFolder'](arg1, arg2);
}

export function CreateIdentity(arg1, arg2) {
  return window['go']['app']['App']['CreateIdentity'](arg1, arg2);
}

export function DeleteDraft(arg1) {
  return window['go']['app']['App']['DeleteDraft'](arg1);
}

export function DeleteIdentity(arg1) {
  return window['go']['app']['App']['DeleteIdentity'](arg1);
}

export function DeletePermanently(arg1) {
  return window['go']['app']['App']['DeletePermanently'](arg1);
}

export function DownloadAttachment(arg1, arg2) {
  return window['go']['app']['App']['DownloadAttachment'](arg1, arg2);
}

export function EmptyTrash(arg1, arg2) {
  return window['go']['app']['App']['EmptyTrash'](arg1, arg2);
}

export function FetchMessageBody(arg1) {
  return window['go']['app']['App']['FetchMessageBody'](arg1);
}

export function FetchServerMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchServerMessage'](arg1, arg2, arg3);
}

export function FindLocalMessageIDs(arg1, arg2, arg3) {
  return window['go']['app']['App']['FindLocalMessageIDs'](arg1, arg2, arg3);
}

export function ForceSyncFolder(arg1, arg2) {
  return window['go']['app']['App']['ForceSyncFolder'](arg1, arg2);
}

export function GetAccentBarUnread() {
  return window['go']['app']['App']['GetAccentBarUnread']();
}

export function GetAccount(arg1) {
  return window['go']['app']['App']['GetAccount'](arg1);
}

export function GetAccountConnOK(arg1) {
  return window['go']['app']['App']['GetAccountConnOK'](arg1);
}

export function GetAccountFoldersForMapping(arg1) {
  return window['go']['app']['App']['GetAccountFoldersForMapping'](arg1);
}

export function GetAccounts() {
  return window['go']['app']['App']['GetAccounts']();
}

export function GetAllAccountIdentities() {
  return window['go']['app']['App']['GetAllAccountIdentities']();
}

export function GetAlwaysLoadImages() {
  return window['go']['app']['App']['GetAlwaysLoadImages']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetAttachments(arg1) {
  return window['go']['app']['App']['GetAttachments'](arg1);
}

export function GetAutoDetectedFolders(arg1) {
  return window['go']['app']['App']['GetAutoDetectedFolders'](arg1);
}

export function GetAutostart() {
  return window['go']['app']['App']['GetAutostart']();
}

export function GetBackupRunState() {
  return window['go']['app']['App']['GetBackupRunState']();
}

export function GetBackupSettings() {
  return window['go']['app']['App']['GetBackupSettings']();
}

export function GetBackupStatus(arg1) {
  return window['go']['app']['App']['GetBackupStatus'](arg1);
}

export function GetBackupViewerCatalog(arg1) {
  return window['go']['app']['App']['GetBackupViewerCatalog'](arg1);
}

export function GetBackupViewerMessage(arg1, arg2) {
  return window['go']['app']['App']['GetBackupViewerMessage'](arg1, arg2);
}

export function GetComposerFormat() {
  return window['go']['app']['App']['GetComposerFormat']();
}

export function GetContactMessages(arg1, arg2) {
  return window['go']['app']['App']['GetContactMessages'](arg1, arg2);
}

export function GetConversation(arg1, arg2) {
  return window['go']['app']['App']['GetConversation'](arg1, arg2);
}

export function GetConversationCount(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetConversationCount'](arg1, arg2, arg3);
}

export function GetConversations(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['GetConversations'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetDarkMailContent() {
  return window['go']['app']['App']['GetDarkMailContent']();
}

export function GetDraft(arg1) {
  return window['go']['app']['App']['GetDraft'](arg1);
}

export function GetFTSIndexStatus(arg1) {
  return window['go']['app']['App']['GetFTSIndexStatus'](arg1);
}

export function GetFolderTree(arg1) {
  return window['go']['app']['App']['GetFolderTree'](arg1);
}

export function GetFolders(arg1) {
  return window['go']['app']['App']['GetFolders'](arg1);
}

export function GetIdentities(arg1) {
  return window['go']['app']['App']['GetIdentities'](arg1);
}

export function GetImageAllowlist() {
  return window['go']['app']['App']['GetImageAllowlist']();
}

export function GetInlineAttachments(arg1) {
  return window['go']['app']['App']['GetInlineAttachments'](arg1);
}

export function GetLanguage() {
  return window['go']['app']['App']['GetLanguage']();
}

export function GetMarkAsReadDelay() {
  return window['go']['app']['App']['GetMarkAsReadDelay']();
}

export function GetMenuBarIcon() {
  return window['go']['app']['App']['GetMenuBarIcon']();
}

export function GetMessageListDensity() {
  return window['go']['app']['App']['GetMessageListDensity']();
}

export function GetMessageListSortOrder() {
  return window['go']['app']['App']['GetMessageListSortOrder']();
}

export function GetMessageSource(arg1) {
  return window['go']['app']['App']['GetMessageSource'](arg1);
}

export function GetNativeTitleBar() {
  return window['go']['app']['App']['GetNativeTitleBar']();
}

export function GetPendingMailto() {
  return window['go']['app']['App']['GetPendingMailto']();
}

export function GetReadReceiptResponsePolicy() {
  return window['go']['app']['App']['GetReadReceiptResponsePolicy']();
}

export function GetRunBackground() {
  return window['go']['app']['App']['GetRunBackground']();
}

export function GetSearchCount(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetSearchCount'](arg1, arg2, arg3, arg4);
}

export function GetSearchCountUnifiedInbox(arg1, arg2) {
  return window['go']['app']['App']['GetSearchCountUnifiedInbox'](arg1, arg2);
}

export function GetShowTitleBar() {
  return window['go']['app']['App']['GetShowTitleBar']();
}

export function GetSpecialFolder(arg1, arg2) {
  return window['go']['app']['App']['GetSpecialFolder'](arg1, arg2);
}

export function GetStartHidden() {
  return window['go']['app']['App']['GetStartHidden']();
}

export function GetStartHiddenActive() {
  return window['go']['app']['App']['GetStartHiddenActive']();
}

export function GetSystemTheme() {
  return window['go']['app']['App']['GetSystemTheme']();
}

export function GetTermsAccepted() {
  return window['go']['app']['App']['GetTermsAccepted']();
}

export function GetThemeMode() {
  return window['go']['app']['App']['GetThemeMode']();
}

export function GetTrustedCertificates(arg1) {
  return window['go']['app']['App']['GetTrustedCertificates'](arg1);
}

export function GetUIState() {
  return window['go']['app']['App']['GetUIState']();
}

export function GetUnifiedInboxConversations(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetUnifiedInboxConversations'](arg1, arg2, arg3, arg4);
}

export function GetUnifiedInboxCount(arg1) {
  return window['go']['app']['App']['GetUnifiedInboxCount'](arg1);
}

export function IMAPSearchFolder(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['IMAPSearchFolder'](arg1, arg2, arg3, arg4);
}

export function IgnoreReadReceipt(arg1, arg2) {
  return window['go']['app']['App']['IgnoreReadReceipt'](arg1, arg2);
}

export function IsFTSIndexing() {
  return window['go']['app']['App']['IsFTSIndexing']();
}

export function IsFlatpak() {
  return window['go']['app']['App']['IsFlatpak']();
}

export function IsImageAllowed(arg1) {
  return window['go']['app']['App']['IsImageAllowed'](arg1);
}

export function IsReady() {
  return window['go']['app']['App']['IsReady']();
}

export function ListEnabledExtensions() {
  return window['go']['app']['App']['ListEnabledExtensions']();
}

export function ListExtensionRailTabs() {
  return window['go']['app']['App']['ListExtensionRailTabs']();
}

export function MarkAllFolderMessagesAsRead(arg1) {
  return window['go']['app']['App']['MarkAllFolderMessagesAsRead'](arg1);
}

export function MarkAllFolderMessagesAsUnread(arg1) {
  return window['go']['app']['App']['MarkAllFolderMessagesAsUnread'](arg1);
}

export function MarkAsNotSpam(arg1) {
  return window['go']['app']['App']['MarkAsNotSpam'](arg1);
}

export function MarkAsRead(arg1) {
  return window['go']['app']['App']['MarkAsRead'](arg1);
}

export function MarkAsSpam(arg1) {
  return window['go']['app']['App']['MarkAsSpam'](arg1);
}

export function MarkAsUnread(arg1) {
  return window['go']['app']['App']['MarkAsUnread'](arg1);
}

export function MoveMessagesToFolder(arg1, arg2) {
  return window['go']['app']['App']['MoveMessagesToFolder'](arg1, arg2);
}

export function MoveToFolder(arg1, arg2) {
  return window['go']['app']['App']['MoveToFolder'](arg1, arg2);
}

export function NotifyStartupComplete() {
  return window['go']['app']['App']['NotifyStartupComplete']();
}

export function OpenAttachment(arg1) {
  return window['go']['app']['App']['OpenAttachment'](arg1);
}

export function OpenBackupDirectory(arg1) {
  return window['go']['app']['App']['OpenBackupDirectory'](arg1);
}

export function OpenBackupViewerDirectory(arg1) {
  return window['go']['app']['App']['OpenBackupViewerDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['app']['App']['OpenURL'](arg1);
}

export function PickAttachmentFiles() {
  return window['go']['app']['App']['PickAttachmentFiles']();
}

export function Preflight() {
  return window['go']['app']['App']['Preflight']();
}

export function PrepareReply(arg1, arg2) {
  return window['go']['app']['App']['PrepareReply'](arg1, arg2);
}

export function QuitApp() {
  return window['go']['app']['App']['QuitApp']();
}

export function ReadFileAsAttachment(arg1) {
  return window['go']['app']['App']['ReadFileAsAttachment'](arg1);
}

export function RefreshContactsFromMail() {
  return window['go']['app']['App']['RefreshContactsFromMail']();
}

export function RefreshWindowConstraints() {
  return window['go']['app']['App']['RefreshWindowConstraints']();
}

export function RemoveAccount(arg1) {
  return window['go']['app']['App']['RemoveAccount'](arg1);
}

export function RemoveImageAllowlist(arg1) {
  return window['go']['app']['App']['RemoveImageAllowlist'](arg1);
}

export function RemoveTrustedCertificate(arg1) {
  return window['go']['app']['App']['RemoveTrustedCertificate'](arg1);
}

export function ReorderAccounts(arg1) {
  return window['go']['app']['App']['ReorderAccounts'](arg1);
}

export function RunEmailBackup(arg1) {
  return window['go']['app']['App']['RunEmailBackup'](arg1);
}

export function SaveAllAttachments(arg1) {
  return window['go']['app']['App']['SaveAllAttachments'](arg1);
}

export function SaveAttachmentAs(arg1) {
  return window['go']['app']['App']['SaveAttachmentAs'](arg1);
}

export function SaveBackupViewerAttachmentAs(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveBackupViewerAttachmentAs'](arg1, arg2, arg3);
}

export function SaveDraft(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveDraft'](arg1, arg2, arg3);
}

export function SaveUIState(arg1) {
  return window['go']['app']['App']['SaveUIState'](arg1);
}

export function SearchBackupViewerMessages(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SearchBackupViewerMessages'](arg1, arg2, arg3, arg4);
}

export function SearchContacts(arg1, arg2) {
  return window['go']['app']['App']['SearchContacts'](arg1, arg2);
}

export function SearchConversations(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['SearchConversations'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SearchMailInAccount(arg1, arg2, arg3) {
  return window['go']['app']['App']['SearchMailInAccount'](arg1, arg2, arg3);
}

export function SearchUnifiedInbox(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SearchUnifiedInbox'](arg1, arg2, arg3, arg4);
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2);
}

export function SendReadReceipt(arg1, arg2) {
  return window['go']['app']['App']['SendReadReceipt'](arg1, arg2);
}

export function SetAccentBarUnread(arg1) {
  return window['go']['app']['App']['SetAccentBarUnread'](arg1);
}

export function SetAlwaysLoadImages(arg1) {
  return window['go']['app']['App']['SetAlwaysLoadImages'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['app']['App']['SetAutostart'](arg1);
}

export function SetBackupSettings(arg1) {
  return window['go']['app']['App']['SetBackupSettings'](arg1);
}

export function SetComposerFormat(arg1) {
  return window['go']['app']['App']['SetComposerFormat'](arg1);
}

export function SetDarkMailContent(arg1) {
  return window['go']['app']['App']['SetDarkMailContent'](arg1);
}

export function SetDefaultIdentity(arg1, arg2) {
  return window['go']['app']['App']['SetDefaultIdentity'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetMarkAsReadDelay(arg1) {
  return window['go']['app']['App']['SetMarkAsReadDelay'](arg1);
}

export function SetMenuBarIcon(arg1) {
  return window['go']['app']['App']['SetMenuBarIcon'](arg1);
}

export function SetMessageListDensity(arg1) {
  return window['go']['app']['App']['SetMessageListDensity'](arg1);
}

export function SetMessageListSortOrder(arg1) {
  return window['go']['app']['App']['SetMessageListSortOrder'](arg1);
}

export function SetNativeTitleBar(arg1) {
  return window['go']['app']['App']['SetNativeTitleBar'](arg1);
}

export function SetReadReceiptResponsePolicy(arg1) {
  return window['go']['app']['App']['SetReadReceiptResponsePolicy'](arg1);
}

export function SetRunBackground(arg1) {
  return window['go']['app']['App']['SetRunBackground'](arg1);
}

export function SetShowTitleBar(arg1) {
  return window['go']['app']['App']['SetShowTitleBar'](arg1);
}

export function SetStartHidden(arg1) {
  return window['go']['app']['App']['SetStartHidden'](arg1);
}

export function SetTermsAccepted(arg1) {
  return window['go']['app']['App']['SetTermsAccepted'](arg1);
}

export function SetThemeMode(arg1) {
  return window['go']['app']['App']['SetThemeMode'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function Star(arg1) {
  return window['go']['app']['App']['Star'](arg1);
}

export function StartEmailBackup(arg1) {
  return window['go']['app']['App']['StartEmailBackup'](arg1);
}

export function SubscribeAllFolders(arg1) {
  return window['go']['app']['App']['SubscribeAllFolders'](arg1);
}

export function SubscribeFolder(arg1, arg2) {
  return window['go']['app']['App']['SubscribeFolder'](arg1, arg2);
}

export function SyncAccountComplete(arg1) {
  return window['go']['app']['App']['SyncAccountComplete'](arg1);
}

export function SyncAllComplete() {
  return window['go']['app']['App']['SyncAllComplete']();
}

export function SyncFolder(arg1, arg2) {
  return window['go']['app']['App']['SyncFolder'](arg1, arg2);
}

export function SyncFolders(arg1) {
  return window['go']['app']['App']['SyncFolders'](arg1);
}

export function SyncPendingDrafts(arg1) {
  return window['go']['app']['App']['SyncPendingDrafts'](arg1);
}

export function TestAccountConnection(arg1) {
  return window['go']['app']['App']['TestAccountConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function Trash(arg1) {
  return window['go']['app']['App']['Trash'](arg1);
}

export function Undo() {
  return window['go']['app']['App']['Undo']();
}

export function Unstar(arg1) {
  return window['go']['app']['App']['Unstar'](arg1);
}

export function UnsubscribeFolder(arg1, arg2) {
  return window['go']['app']['App']['UnsubscribeFolder'](arg1, arg2);
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['app']['App']['UpdateAccount'](arg1, arg2);
}

export function UpdateIdentity(arg1, arg2) {
  return window['go']['app']['App']['UpdateIdentity'](arg1, arg2);
}
