// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {certificate} from '../models';
import {account} from '../models';
import {v1} from '../models';
import {message} from '../models';
import {folder} from '../models';
import {app} from '../models';
import {smtp} from '../models';
import {settings} from '../models';
import {appstate} from '../models';
import {sync} from '../models';
import {contact} from '../models';

export function AcceptCertificate(arg1:string,arg2:certificate.CertificateInfo,arg3:boolean):Promise<void>;

export function AddAccount(arg1:account.AccountConfig):Promise<account.Account>;

export function AddImageAllowlist(arg1:string,arg2:string):Promise<void>;

export function Archive(arg1:Array<string>):Promise<void>;

export function CancelAllSyncs():Promise<void>;

export function CancelFolderSync(arg1:string,arg2:string):Promise<void>;

export function ChooseBackupDirectory():Promise<string>;

export function Contacts_CreateContact(arg1:v1.ContactCreateInput):Promise<string>;

export function Contacts_DeleteLocalContact(arg1:string):Promise<void>;

export function Contacts_GetContactAccountGroups():Promise<Array<v1.ContactAccountGroup>>;

export function Contacts_GetContactDetail(arg1:string):Promise<v1.Contact>;

export function Contacts_ListContactsForBrowse(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<v1.Contact>>;

export function Contacts_UpdateContact(arg1:string,arg2:v1.ContactPatch):Promise<void>;

export function CopyToFolder(arg1:Array<string>,arg2:string):Promise<void>;

export function CreateIdentity(arg1:string,arg2:account.IdentityConfig):Promise<account.Identity>;

export function DeleteDraft(arg1:string):Promise<void>;

export function DeleteIdentity(arg1:string):Promise<void>;

export function DeletePermanently(arg1:Array<string>):Promise<void>;

export function DownloadAttachment(arg1:string,arg2:string):Promise<string>;

export function EmptyTrash(arg1:string,arg2:string):Promise<void>;

export function FetchMessageBody(arg1:string):Promise<message.Message>;

export function FetchServerMessage(arg1:string,arg2:string,arg3:number):Promise<message.Message>;

export function FindLocalMessageIDs(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<string>>;

export function ForceSyncFolder(arg1:string,arg2:string):Promise<void>;

export function GetAccentBarUnread():Promise<boolean>;

export function GetAccount(arg1:string):Promise<account.Account>;

export function GetAccountConnOK(arg1:string):Promise<string>;

export function GetAccountFoldersForMapping(arg1:string):Promise<Array<folder.Folder>>;

export function GetAccounts():Promise<Array<account.Account>>;

export function GetAllAccountIdentities():Promise<Array<app.AccountIdentityGroup>>;

export function GetAlwaysLoadImages():Promise<boolean>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetAttachments(arg1:string):Promise<Array<message.Attachment>>;

export function GetAutoDetectedFolders(arg1:string):Promise<Record<string, string>>;

export function GetAutostart():Promise<boolean>;

export function GetBackupRunState():Promise<app.BackupRunState>;

export function GetBackupSettings():Promise<app.BackupSettings>;

export function GetBackupStatus(arg1:string):Promise<app.BackupStatus>;

export function GetBackupViewerCatalog(arg1:string):Promise<app.BackupViewerCatalog>;

export function GetBackupViewerMessage(arg1:string,arg2:string):Promise<app.BackupViewerMessageDetail>;

export function GetComposerFormat():Promise<string>;

export function GetContactMessages(arg1:string,arg2:number):Promise<Array<message.ContactMessage>>;

export function GetConversation(arg1:string,arg2:string):Promise<message.Conversation>;

export function GetConversationCount(arg1:string,arg2:string,arg3:string):Promise<number>;

export function GetConversations(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string):Promise<Array<message.Conversation>>;

export function GetDarkMailContent():Promise<boolean>;

export function GetDraft(arg1:string):Promise<smtp.ComposeMessage>;

export function GetFTSIndexStatus(arg1:string):Promise<message.FTSIndexStatus>;

export function GetFolderTree(arg1:string):Promise<Array<folder.FolderTree>>;

export function GetFolders(arg1:string):Promise<Array<folder.Folder>>;

export function GetIdentities(arg1:string):Promise<Array<account.Identity>>;

export function GetImageAllowlist():Promise<Array<settings.AllowlistEntry>>;

export function GetInlineAttachments(arg1:string):Promise<Record<string, string>>;

export function GetLanguage():Promise<string>;

export function GetMarkAsReadDelay():Promise<number>;

export function GetMenuBarIcon():Promise<boolean>;

export function GetMessageListDensity():Promise<string>;

export function GetMessageListSortOrder():Promise<string>;

export function GetMessageSource(arg1:string):Promise<string>;

export function GetNativeTitleBar():Promise<boolean>;

export function GetPendingMailto():Promise<app.MailtoData>;

export function GetReadReceiptResponsePolicy():Promise<string>;

export function GetRunBackground():Promise<boolean>;

export function GetSearchCount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function GetSearchCountUnifiedInbox(arg1:string,arg2:string):Promise<number>;

export function GetShowTitleBar():Promise<boolean>;

export function GetSpecialFolder(arg1:string,arg2:folder.Type):Promise<folder.Folder>;

export function GetStartHidden():Promise<boolean>;

export function GetStartHiddenActive():Promise<boolean>;

export function GetSystemTheme():Promise<string>;

export function GetTermsAccepted():Promise<boolean>;

export function GetThemeMode():Promise<string>;

export function GetTrustedCertificates(arg1:Array<string>):Promise<Array<certificate.CertificateInfo>>;

export function GetUIState():Promise<appstate.UIState>;

export function GetUnifiedInboxConversations(arg1:number,arg2:number,arg3:string,arg4:string):Promise<Array<message.Conversation>>;

export function GetUnifiedInboxCount(arg1:string):Promise<number>;

export function IMAPSearchFolder(arg1:string,arg2:string,arg3:string,arg4:number):Promise<sync.IMAPSearchResponse>;

export function IgnoreReadReceipt(arg1:string,arg2:string):Promise<void>;

export function IsFTSIndexing():Promise<boolean>;

export function IsFlatpak():Promise<boolean>;

export function IsImageAllowed(arg1:string):Promise<boolean>;

export function IsReady():Promise<boolean>;

export function ListEnabledExtensions():Promise<Array<string>>;

export function ListExtensionRailTabs():Promise<Array<v1.RailTabRequest>>;

export function MarkAllFolderMessagesAsRead(arg1:string):Promise<void>;

export function MarkAllFolderMessagesAsUnread(arg1:string):Promise<void>;

export function MarkAsNotSpam(arg1:Array<string>):Promise<void>;

export function MarkAsRead(arg1:Array<string>):Promise<void>;

export function MarkAsSpam(arg1:Array<string>):Promise<boolean>;

export function MarkAsUnread(arg1:Array<string>):Promise<void>;

export function MoveMessagesToFolder(arg1:Array<string>,arg2:string):Promise<void>;

export function MoveToFolder(arg1:Array<string>,arg2:string):Promise<void>;

export function NotifyStartupComplete():Promise<void>;

export function OpenAttachment(arg1:string):Promise<void>;

export function OpenBackupDirectory(arg1:string):Promise<void>;

export function OpenBackupViewerDirectory(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PickAttachmentFiles():Promise<Array<app.ComposerAttachment>>;

export function Preflight():Promise<void>;

export function PrepareReply(arg1:string,arg2:string):Promise<smtp.ComposeMessage>;

export function QuitApp():Promise<void>;

export function ReadFileAsAttachment(arg1:string):Promise<app.ComposerAttachment>;

export function RefreshContactsFromMail():Promise<number>;

export function RefreshWindowConstraints():Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RemoveImageAllowlist(arg1:number):Promise<void>;

export function RemoveTrustedCertificate(arg1:string):Promise<void>;

export function ReorderAccounts(arg1:Array<string>):Promise<void>;

export function RunEmailBackup(arg1:app.BackupRunOptions):Promise<app.BackupRunResult>;

export function SaveAllAttachments(arg1:string):Promise<string>;

export function SaveAttachmentAs(arg1:string):Promise<string>;

export function SaveBackupViewerAttachmentAs(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SaveDraft(arg1:string,arg2:smtp.ComposeMessage,arg3:string):Promise<app.DraftResult>;

export function SaveUIState(arg1:appstate.UIState):Promise<void>;

export function SearchBackupViewerMessages(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<app.BackupViewerMessageSummary>>;

export function SearchContacts(arg1:string,arg2:number):Promise<Array<contact.Contact>>;

export function SearchConversations(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<Array<message.ConversationSearchResult>>;

export function SearchMailInAccount(arg1:string,arg2:string,arg3:number):Promise<Array<message.ContactMessage>>;

export function SearchUnifiedInbox(arg1:string,arg2:number,arg3:number,arg4:string):Promise<Array<message.ConversationSearchResult>>;

export function SendMessage(arg1:string,arg2:smtp.ComposeMessage):Promise<void>;

export function SendReadReceipt(arg1:string,arg2:string):Promise<void>;

export function SetAccentBarUnread(arg1:boolean):Promise<void>;

export function SetAlwaysLoadImages(arg1:boolean):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetBackupSettings(arg1:app.BackupSettings):Promise<void>;

export function SetComposerFormat(arg1:string):Promise<void>;

export function SetDarkMailContent(arg1:boolean):Promise<void>;

export function SetDefaultIdentity(arg1:string,arg2:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetMarkAsReadDelay(arg1:number):Promise<void>;

export function SetMenuBarIcon(arg1:boolean):Promise<void>;

export function SetMessageListDensity(arg1:string):Promise<void>;

export function SetMessageListSortOrder(arg1:string):Promise<void>;

export function SetNativeTitleBar(arg1:boolean):Promise<void>;

export function SetReadReceiptResponsePolicy(arg1:string):Promise<void>;

export function SetRunBackground(arg1:boolean):Promise<void>;

export function SetShowTitleBar(arg1:boolean):Promise<void>;

export function SetStartHidden(arg1:boolean):Promise<void>;

export function SetTermsAccepted(arg1:boolean):Promise<void>;

export function SetThemeMode(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function Star(arg1:Array<string>):Promise<void>;

export function StartEmailBackup(arg1:app.BackupRunOptions):Promise<app.BackupRunState>;

export function SubscribeAllFolders(arg1:string):Promise<void>;

export function SubscribeFolder(arg1:string,arg2:string):Promise<void>;

export function SyncAccountComplete(arg1:string):Promise<void>;

export function SyncAllComplete():Promise<void>;

export function SyncFolder(arg1:string,arg2:string):Promise<void>;

export function SyncFolders(arg1:string):Promise<void>;

export function SyncPendingDrafts(arg1:string):Promise<void>;

export function TestAccountConnection(arg1:string):Promise<app.ConnectionTestResult>;

export function TestConnection(arg1:account.AccountConfig):Promise<app.ConnectionTestResult>;

export function Trash(arg1:Array<string>):Promise<boolean>;

export function Undo():Promise<string>;

export function Unstar(arg1:Array<string>):Promise<void>;

export function UnsubscribeFolder(arg1:string,arg2:string):Promise<void>;

export function UpdateAccount(arg1:string,arg2:account.AccountConfig):Promise<account.Account>;

export function UpdateIdentity(arg1:string,arg2:account.IdentityConfig):Promise<account.Identity>;
