// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['app']['ComposerApp']['CloseWindow']();
}

export function DeleteDraft(arg1) {
  return window['go']['app']['ComposerApp']['DeleteDraft'](arg1);
}

export function GetAccount(arg1) {
  return window['go']['app']['ComposerApp']['GetAccount'](arg1);
}

export function GetAllAccountIdentities() {
  return window['go']['app']['ComposerApp']['GetAllAccountIdentities']();
}

export function GetComposeMode() {
  return window['go']['app']['ComposerApp']['GetComposeMode']();
}

export function GetDraft() {
  return window['go']['app']['ComposerApp']['GetDraft']();
}

export function GetIdentities(arg1) {
  return window['go']['app']['ComposerApp']['GetIdentities'](arg1);
}

export function GetNativeTitleBar() {
  return window['go']['app']['ComposerApp']['GetNativeTitleBar']();
}

export function GetOriginalMessage() {
  return window['go']['app']['ComposerApp']['GetOriginalMessage']();
}

export function GetShowTitleBar() {
  return window['go']['app']['ComposerApp']['GetShowTitleBar']();
}

export function GetSystemTheme() {
  return window['go']['app']['ComposerApp']['GetSystemTheme']();
}

export function GetThemeMode() {
  return window['go']['app']['ComposerApp']['GetThemeMode']();
}

export function IsFlatpak() {
  return window['go']['app']['ComposerApp']['IsFlatpak']();
}

export function LogFrontend(arg1, arg2) {
  return window['go']['app']['ComposerApp']['LogFrontend'](arg1, arg2);
}

export function NotifyStartupComplete() {
  return window['go']['app']['ComposerApp']['NotifyStartupComplete']();
}

export function PickAttachmentFiles() {
  return window['go']['app']['ComposerApp']['PickAttachmentFiles']();
}

export function PrepareReply() {
  return window['go']['app']['ComposerApp']['PrepareReply']();
}

export function ReadFileAsAttachment(arg1) {
  return window['go']['app']['ComposerApp']['ReadFileAsAttachment'](arg1);
}

export function RefreshWindowConstraints() {
  return window['go']['app']['ComposerApp']['RefreshWindowConstraints']();
}

export function SaveDraft(arg1, arg2, arg3) {
  return window['go']['app']['ComposerApp']['SaveDraft'](arg1, arg2, arg3);
}

export function SearchContacts(arg1, arg2) {
  return window['go']['app']['ComposerApp']['SearchContacts'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['ComposerApp']['SendMessage'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['app']['ComposerApp']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['ComposerApp']['Startup'](arg1);
}
