// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';
import {app} from '../models';
import {smtp} from '../models';
import {message} from '../models';
import {draft} from '../models';
import {contact} from '../models';
import {context} from '../models';

export function CloseWindow():Promise<void>;

export function DeleteDraft(arg1:string):Promise<void>;

export function GetAccount(arg1:string):Promise<account.Account>;

export function GetAllAccountIdentities():Promise<Array<app.AccountIdentityGroup>>;

export function GetComposeMode():Promise<app.ComposeMode>;

export function GetDraft():Promise<smtp.ComposeMessage>;

export function GetIdentities(arg1:string):Promise<Array<account.Identity>>;

export function GetNativeTitleBar():Promise<boolean>;

export function GetOriginalMessage():Promise<message.Message>;

export function GetShowTitleBar():Promise<boolean>;

export function GetSystemTheme():Promise<string>;

export function GetThemeMode():Promise<string>;

export function IsFlatpak():Promise<boolean>;

export function LogFrontend(arg1:string,arg2:string):Promise<void>;

export function NotifyStartupComplete():Promise<void>;

export function PickAttachmentFiles():Promise<Array<app.ComposerAttachment>>;

export function PrepareReply():Promise<smtp.ComposeMessage>;

export function ReadFileAsAttachment(arg1:string):Promise<app.ComposerAttachment>;

export function RefreshWindowConstraints():Promise<void>;

export function SaveDraft(arg1:string,arg2:smtp.ComposeMessage,arg3:string):Promise<draft.Draft>;

export function SearchContacts(arg1:string,arg2:number):Promise<Array<contact.Contact>>;

export function SendMessage(arg1:string,arg2:smtp.ComposeMessage):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
