<script lang="ts">
  import { onDestroy, onMount } from 'svelte'
  import Icon from '@iconify/svelte'
  import BackupDirectoryPicker from '$lib/components/backup/BackupDirectoryPicker.svelte'
  import { Button } from '$lib/components/ui/button'
  import { Label } from '$lib/components/ui/label'
  import { accountStore } from '$lib/stores/accounts.svelte'
  import { addToast } from '$lib/stores/toast'
  import { _ } from '$lib/i18n'
  import {
    rememberBackupDirectory,
    removeBackupDirectory,
  } from '$lib/utils/backup-directory-history'
  import { formatLocalDateTime } from '$lib/utils/date'
  // @ts-ignore - wailsjs path
  import { GetBackupRunState, GetBackupSettings, GetBackupStatus, OpenBackupDirectory, SetBackupSettings, StartEmailBackup } from '../../../../wailsjs/go/app/App.js'
  // @ts-ignore - wailsjs path
  import { EventsOn } from '../../../../wailsjs/runtime/runtime'
  // @ts-ignore - generated by Wails
  import type { app } from '../../../../wailsjs/go/models'

  const backupScopeAll = 'all'
  const backupScopeSelected = 'selected'

  type BackupProgress = {
    phase: string
    accountEmail?: string
    folderPath?: string
    current: number
    total: number
    exported: number
    skipped: number
    missing?: number
    failed: number
    message?: string
  }

  let loading = $state(true)
  let saving = $state(false)
  let running = $state(false)
  let directory = $state('')
  let scope = $state(backupScopeAll)
  let selectedAccountIds = $state<string[]>([])
  let scopeMenuOpen = $state(false)
  let scopeMenuEl = $state<HTMLDivElement | null>(null)
  let status = $state<app.BackupStatus | null>(null)
  let progress = $state<BackupProgress | null>(null)
  let unsubscribeProgress: (() => void) | undefined

  const regularAccounts = $derived(accountStore.accounts.filter(acc => !acc.account.sharedMailboxParentId))
  const regularAccountIds = $derived(regularAccounts.map(acc => acc.account.id))
  const selectedBackupAccountIds = $derived(
    scope === backupScopeAll
      ? regularAccountIds
      : selectedAccountIds.filter(id => regularAccountIds.includes(id)),
  )
  const selectedAccountSet = $derived(new Set(selectedBackupAccountIds))
  const selectedAccountsCount = $derived(selectedBackupAccountIds.length)
  const allMailboxesSelected = $derived(
    regularAccounts.length > 0 && selectedAccountsCount === regularAccounts.length,
  )
  const scopeLabel = $derived.by(() => {
    if (scope === backupScopeAll || allMailboxesSelected) return $_('settingsBackup.scopeAll')
    if (selectedAccountsCount === 0) return $_('settingsBackup.scopeSelected')
    if (selectedAccountsCount === 1) {
      const id = selectedBackupAccountIds[0]
      return regularAccounts.find(acc => acc.account.id === id)?.account.email ?? $_('settingsBackup.selectedMailboxes', { values: { count: selectedAccountsCount } })
    }
    return $_('settingsBackup.selectedMailboxes', { values: { count: selectedAccountsCount } })
  })

  function sameIds(a: string[], b: string[]): boolean {
    return a.length === b.length && a.every((id, index) => id === b[index])
  }

  function getModeLabel(mode: string | undefined): string {
    return mode === 'incremental' ? $_('settingsBackup.incrementalExport') : $_('settingsBackup.fullExport')
  }

  function formatLastRun(value: string | undefined): string {
    if (!value) return $_('settingsBackup.neverRun')
    try {
      return formatLocalDateTime(value)
    } catch {
      return value
    }
  }

  function formatProgressMessage(): string {
    if (!progress) return ''
    const current = progress.total > 0 ? `${progress.current}/${progress.total}` : '0/0'
    const target = [progress.accountEmail, progress.folderPath].filter(Boolean).join(' / ')
    return target ? `${current} · ${target}` : current
  }

  function formatProgressCounts(): string {
    if (!progress) return ''
    const missing = progress.missing ?? 0
    if (missing > 0) {
      return $_('settingsBackup.progressCountsWithMissing', {
        values: {
          exported: progress.exported,
          skipped: progress.skipped,
          missing,
          failed: progress.failed,
        },
      })
    }
    return $_('settingsBackup.progressCounts', {
      values: {
        exported: progress.exported,
        skipped: progress.skipped,
        failed: progress.failed,
      },
    })
  }

  function isBackupAlreadyRunningError(err: unknown): boolean {
    return String(err).includes('email backup is already running')
  }

  async function refreshRunState() {
    try {
      const runState = await GetBackupRunState()
      running = Boolean(runState?.running)
      progress = runState?.progress ?? null
    } catch (err) {
      console.error('Failed to load backup run state:', err)
    }
  }

  async function loadBackupSettings() {
    loading = true
    try {
      const cfg = await GetBackupSettings()
      directory = cfg?.directory ?? ''
      if (directory) {
        rememberBackupDirectory(directory)
      }
      scope = cfg?.scope === backupScopeSelected ? backupScopeSelected : backupScopeAll
      selectedAccountIds = cfg?.selectedAccountIds ?? []
      await refreshStatus()
      await refreshRunState()
    } catch (err) {
      console.error('Failed to load backup settings:', err)
      addToast({ type: 'error', message: $_('settingsBackup.loadFailed') })
    } finally {
      loading = false
    }
  }

  async function refreshStatus() {
    if (!directory) {
      status = { directory: '', mode: 'full', hasIndex: false, messageCount: 0, lastRunAt: '', lastRunMode: '', lastRunResult: '' } as app.BackupStatus
      return
    }
    try {
      status = await GetBackupStatus(directory)
    } catch (err) {
      console.error('Failed to load backup status:', err)
      status = null
    }
  }

  async function saveBackupSettings() {
    saving = true
    try {
      await SetBackupSettings({
        directory,
        scope,
        selectedAccountIds,
      })
    } finally {
      saving = false
    }
  }

  $effect(() => {
    const validAccountIds = new Set(regularAccountIds)
    const filtered = selectedAccountIds.filter(id => validAccountIds.has(id))
    const normalized = scope === backupScopeAll ? regularAccountIds : filtered
    if (!sameIds(normalized, selectedAccountIds)) {
      selectedAccountIds = normalized
    }
  })

  function handleWindowPointerDown(event: PointerEvent) {
    if (!scopeMenuOpen) return
    const target = event.target
    if (target instanceof Node && scopeMenuEl?.contains(target)) return
    scopeMenuOpen = false
  }

  async function applyDirectory(nextDirectory: string, options: { fromHistory?: boolean } = {}) {
    const normalized = nextDirectory.trim()
    if (!normalized) return
    const previousDirectory = directory
    directory = normalized
    try {
      await saveBackupSettings()
      await refreshStatus()
      rememberBackupDirectory(directory)
      addToast({ type: 'success', message: $_('settingsBackup.settingsSaved') })
    } catch (err) {
      console.error('Failed to apply backup directory:', err)
      directory = previousDirectory
      await refreshStatus()
      if (options.fromHistory) {
        removeBackupDirectory(normalized)
        addToast({
          type: 'error',
          message: $_('backupViewer.historyPathMissing', { values: { path: normalized } }),
        })
      } else {
        addToast({ type: 'error', message: $_('settingsBackup.chooseDirectoryFailed') })
      }
    }
  }

  function handleChooseDirectoryError() {
    addToast({ type: 'error', message: $_('settingsBackup.chooseDirectoryFailed') })
  }

  async function handleOpenDirectory() {
    if (!directory) {
      addToast({ type: 'error', message: $_('settingsBackup.selectDirectoryFirst') })
      return
    }
    try {
      await OpenBackupDirectory(directory)
    } catch (err) {
      console.error('Failed to open backup directory:', err)
      addToast({ type: 'error', message: $_('settingsBackup.openDirectoryFailed') })
    }
  }

  async function selectAllAccounts() {
    scope = backupScopeAll
    selectedAccountIds = regularAccountIds
    try {
      await saveBackupSettings()
    } catch (err) {
      console.error('Failed to save backup scope:', err)
      addToast({ type: 'error', message: $_('settingsBackup.saveFailed') })
    }
  }

  async function toggleAccount(accountId: string) {
    const next = new Set(selectedBackupAccountIds)
    if (next.has(accountId)) {
      next.delete(accountId)
    } else {
      next.add(accountId)
    }
    const nextIds = regularAccountIds.filter(id => next.has(id))
    selectedAccountIds = nextIds
    scope = nextIds.length === regularAccounts.length ? backupScopeAll : backupScopeSelected
    try {
      await saveBackupSettings()
    } catch (err) {
      console.error('Failed to save selected backup accounts:', err)
      addToast({ type: 'error', message: $_('settingsBackup.saveFailed') })
    }
  }

  async function handleRunBackup() {
    if (running) {
      addToast({ type: 'warning', message: $_('settingsBackup.backupAlreadyRunning') })
      return
    }
    if (!directory) {
      addToast({ type: 'error', message: $_('settingsBackup.selectDirectoryFirst') })
      return
    }
    if (scope === backupScopeSelected && selectedAccountIds.length === 0) {
      addToast({ type: 'error', message: $_('settingsBackup.selectMailboxFirst') })
      return
    }
    running = true
    progress = { phase: 'running', current: 0, total: 0, exported: 0, skipped: 0, missing: 0, failed: 0 }
    try {
      await saveBackupSettings()
      const runState = await StartEmailBackup({ directory, scope, selectedAccountIds })
      running = Boolean(runState?.running)
      progress = runState?.progress ?? progress
      addToast({ type: 'success', message: $_('settingsBackup.backupStartedInBackground') })
    } catch (err) {
      console.error('Failed to run backup:', err)
      if (isBackupAlreadyRunningError(err)) {
        addToast({ type: 'warning', message: $_('settingsBackup.backupAlreadyRunning') })
      } else {
        addToast({ type: 'error', message: $_('settingsBackup.backupFailed') })
      }
    } finally {
      await refreshRunState()
    }
  }

  onMount(() => {
    window.addEventListener('pointerdown', handleWindowPointerDown, true)
    unsubscribeProgress = EventsOn('backup:progress', (data: BackupProgress) => {
      progress = data
      running = data.phase === 'running'
      if (data.phase === 'done' || data.phase === 'error') {
        void refreshStatus()
      }
    })
    loadBackupSettings()
  })

  onDestroy(() => {
    window.removeEventListener('pointerdown', handleWindowPointerDown, true)
    unsubscribeProgress?.()
  })
</script>

{#if loading}
  <div class="flex items-center justify-center py-8">
    <Icon icon="mdi:loading" class="w-6 h-6 animate-spin text-muted-foreground" />
  </div>
{:else}
  <div class="space-y-4">
    <div class="flex items-center justify-between gap-4">
      <div class="min-w-0">
        <Label>{$_('settingsBackup.directory')}</Label>
      </div>
      <div class="w-[28rem] max-w-full shrink-0">
        <BackupDirectoryPicker
          {directory}
          placeholder={$_('settingsBackup.directoryPlaceholder')}
          disabled={running || saving}
          openDisabled={running || saving}
          onChoose={(path) => applyDirectory(path)}
          onChooseError={handleChooseDirectoryError}
          onSelectHistory={(path) => applyDirectory(path, { fromHistory: true })}
          onOpenDirectory={() => handleOpenDirectory()}
        />
      </div>
    </div>

    <div class="flex items-center justify-between gap-4">
      <div class="min-w-0">
        <Label>{$_('settingsBackup.scope')}</Label>
      </div>
      <div
        bind:this={scopeMenuEl}
        class="relative w-[28rem] max-w-full shrink-0"
      >
        <button
          type="button"
          class="flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-left text-sm text-foreground ring-offset-background transition-colors hover:bg-accent/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
          onclick={() => scopeMenuOpen = !scopeMenuOpen}
          onkeydown={(event) => {
            if (event.key === 'Escape') scopeMenuOpen = false
          }}
          disabled={running || saving || regularAccounts.length === 0}
          aria-haspopup="listbox"
          aria-expanded={scopeMenuOpen}
        >
          <span class="min-w-0 truncate">{regularAccounts.length === 0 ? $_('settingsBackup.noAccounts') : scopeLabel}</span>
          <Icon icon="mdi:chevron-down" class="h-4 w-4 shrink-0 opacity-50" />
        </button>
        {#if scopeMenuOpen}
          <div
            class="absolute right-0 z-50 mt-1 max-h-64 w-full overflow-y-auto rounded-md border border-border bg-popover p-1 text-popover-foreground shadow-lg"
            role="listbox"
            aria-multiselectable="true"
            tabindex="-1"
            onkeydown={(event) => {
              if (event.key === 'Escape') {
                event.stopPropagation()
                scopeMenuOpen = false
              }
            }}
          >
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-left text-sm outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
              onclick={selectAllAccounts}
              role="option"
              aria-selected={allMailboxesSelected}
            >
              <Icon icon={allMailboxesSelected ? 'mdi:check' : 'mdi:checkbox-blank-outline'} class="h-4 w-4 shrink-0 text-primary" />
              <span class="min-w-0 flex-1 truncate">{$_('settingsBackup.scopeAll')}</span>
            </button>
            {#each regularAccounts as item (item.account.id)}
              {@const account = item.account}
              {@const selected = selectedAccountSet.has(account.id)}
              <button
                type="button"
                class="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-left text-sm outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
                onclick={() => toggleAccount(account.id)}
                role="option"
                aria-selected={selected}
              >
                <Icon icon={selected ? 'mdi:checkbox-marked' : 'mdi:checkbox-blank-outline'} class="h-4 w-4 shrink-0 text-primary" />
                <span class="min-w-0 flex-1 truncate">{account.email}</span>
              </button>
            {/each}
          </div>
        {/if}
      </div>
    </div>

    <div class="flex items-center justify-between gap-4">
      <div class="min-w-0">
        <Label>{$_('settingsBackup.backupStatus')}</Label>
      </div>
      <div class="w-[28rem] max-w-full shrink-0 rounded-md border border-border bg-muted/20 px-3 py-2 text-sm">
        <div class="flex items-center justify-between gap-3">
          <span class="font-medium">{getModeLabel(status?.mode)}</span>
          <span class="text-xs text-muted-foreground">{$_('settingsBackup.selectedMailboxes', { values: { count: selectedAccountsCount } })}</span>
        </div>
        <div class="mt-1 text-xs text-muted-foreground">
          {#if status?.hasIndex}
            {$_('settingsBackup.indexedMessages', { values: { count: status.messageCount } })} · {$_('settingsBackup.lastRun')} {formatLastRun(status.lastRunAt)}
          {:else}
            {$_('settingsBackup.directoryChangedHint')}
          {/if}
        </div>
      </div>
    </div>

    {#if running || progress}
      <div class="rounded-md border border-border bg-muted/20 px-3 py-2 text-sm">
        <div class="flex items-center gap-2">
          {#if running}
            <Icon icon="mdi:loading" class="h-4 w-4 animate-spin text-primary" />
          {:else}
            <Icon icon={progress?.failed ? 'mdi:alert-circle-outline' : 'mdi:check-circle-outline'} class="h-4 w-4 text-primary" />
          {/if}
          <span>{formatProgressMessage()}</span>
        </div>
        {#if progress && progress.total > 0}
          <div class="mt-2 h-1.5 overflow-hidden rounded-full bg-muted">
            <div
              class="h-full rounded-full bg-primary transition-all"
              style={`width: ${Math.min(100, Math.round((progress.current / progress.total) * 100))}%`}
            ></div>
          </div>
          <div class="mt-1 text-xs text-muted-foreground">
            {formatProgressCounts()}
          </div>
        {/if}
      </div>
    {/if}

    <div class="flex items-center justify-between gap-4">
      <div class="min-w-0"></div>
      <div class="flex w-[28rem] max-w-full shrink-0 justify-end">
        <Button onclick={handleRunBackup} disabled={running || saving || !directory || regularAccounts.length === 0}>
          {#if running}
            <Icon icon="mdi:loading" class="mr-2 h-4 w-4 animate-spin" />
            {$_('settingsBackup.backupRunning')}
          {:else}
            <Icon icon="mdi:archive-arrow-down-outline" class="mr-2 h-4 w-4" />
            {$_('settingsBackup.startBackup')}
          {/if}
        </Button>
      </div>
    </div>
  </div>
{/if}
