<script lang="ts">
  import Icon from '@iconify/svelte'
  import { tick, untrack } from 'svelte'
  import * as Dialog from '$lib/components/ui/dialog'
  import ConfirmDialog from '$lib/components/ui/confirm-dialog/ConfirmDialog.svelte'
  import { addToast } from '$lib/stores/toast'
  import { dialogGuardClose, dialogGuardOpen } from '$lib/stores/dialogGuard'
  import { isInputElement, setKeyboardScope } from '$lib/stores/keyboard.svelte'
  import { nextRovingIndex, type RovingNavigationKey } from '$lib/keyboard/regionNavigation'
  import { resolveHorizontalActionIndex } from '$lib/keyboard/settingsHorizontalNavigation'
  import { getEnhancedKeyboardNavigation } from '$lib/stores/settings.svelte'
  import { keyboardActionMenu } from '$lib/stores/keyboardActionMenu.svelte'
  import { _ } from '$lib/i18n'
  // @ts-ignore - generated by Wails
  import { GetAppInfo, QuitApp } from '../../../../wailsjs/go/app/App.js'
  import type { app } from '../../../../wailsjs/go/models'
  import { SettingsDraft } from './settingsDraft.svelte'
  import GeneralSettingsPage from './pages/GeneralSettingsPage.svelte'
  import AppearanceSettingsPage from './pages/AppearanceSettingsPage.svelte'
  import MailSettingsPage from './pages/MailSettingsPage.svelte'
  import AccountsSettingsPage from './pages/AccountsSettingsPage.svelte'
  import BackupSettingsPage from './backup/BackupSettingsPage.svelte'
  import ActivityLogPage from './activity/ActivityLogPage.svelte'
  import AboutTab from './AboutTab.svelte'
  import UpdateAction from './UpdateAction.svelte'

  type SettingsPage = 'general' | 'appearance' | 'mail' | 'accounts' | 'backup' | 'activity' | 'about'
  type SettingsContentItem = { kind: 'control'; element: HTMLElement }
  interface NavigationItem { id: SettingsPage; icon: string; label: string }
  interface Props { open?: boolean; activePage?: SettingsPage; onClose?: () => void }
  let { open = $bindable(false), activePage = $bindable('general'), onClose }: Props = $props()
  const draft = new SettingsDraft()
  let appInfo = $state<app.AppInfo | null>(null)
  let appInfoLoading = $state(false)
  let showRestartDialog = $state(false)
  let activityInitialType = $state('')
  let loadSequence = 0
  let settingsRegion = $state<'navigation' | 'content'>('navigation')
  let settingsContentMode = $state<'browse' | 'input'>('browse')
  let settingsNavigationInputMode = $state<'keyboard' | 'pointer'>('pointer')
  let selectedNavigationPage = $state<SettingsPage>('general')
  let selectedSettingsControlIndex = $state(0)
  let navigationRegionEl = $state<HTMLElement | null>(null)
  let contentRegionEl = $state<HTMLElement | null>(null)
  let contentPanelEl = $state<HTMLElement | null>(null)
  let closeButtonEl = $state<HTMLButtonElement | null>(null)
  let selectStateObserver: MutationObserver | null = null
  let autoSaveBlocked = $state(false)
  let closeInProgress = false
  let autoSavePromise: Promise<void> | null = null

  const SETTINGS_CONTROL_SELECTOR = [
    'button:not(:disabled):not([aria-disabled="true"])',
    'a[href]',
    'input:not(:disabled):not([type="hidden"])',
    'textarea:not(:disabled)',
    'select:not(:disabled)',
    '[role="button"]:not([aria-disabled="true"])',
    '[role="combobox"]:not([aria-disabled="true"])',
    '[role="checkbox"]:not([aria-disabled="true"])',
    '[contenteditable="true"]',
  ].join(',')

  const navigation: NavigationItem[] = $derived([
    { id: 'general', icon: 'lucide:settings-2', label: $_('settings.general') },
    { id: 'appearance', icon: 'lucide:palette', label: $_('settings.appearance') },
    { id: 'mail', icon: 'lucide:mail', label: $_('settings.mail') },
    { id: 'accounts', icon: 'lucide:mails', label: $_('settings.accounts') },
    { id: 'backup', icon: 'lucide:archive', label: $_('settings.backup') },
    { id: 'activity', icon: 'lucide:history', label: $_('activityLog.title') },
    { id: 'about', icon: 'lucide:info', label: $_('settings.about') },
  ])
  $effect(() => {
    if (!open) return
    const sequence = ++loadSequence
    autoSaveBlocked = false
    appInfoLoading = true
    draft.load().catch((error) => {
      if (sequence !== loadSequence) return
      console.error('Failed to load settings:', error)
      addToast({ type: 'error', message: $_('toast.failedToLoadSettings') })
    })
    GetAppInfo().then((info) => {
      if (sequence === loadSequence) appInfo = info
    }).catch((error) => {
      if (sequence !== loadSequence) return
      appInfo = null
      console.error('Failed to load app info:', error)
    }).finally(() => {
      if (sequence === loadSequence) appInfoLoading = false
    })
  })

  $effect(() => {
    if (!open) return
    settingsRegion = 'navigation'
    settingsContentMode = 'browse'
    selectedNavigationPage = untrack(() => activePage)
    selectedSettingsControlIndex = 0
    setKeyboardScope('settings')
    return () => {
      stopObservingSelectLifecycle()
      setKeyboardScope('main')
    }
  })

  $effect(() => {
    if (
      !open
      || !getEnhancedKeyboardNavigation()
      || draft.loading
      || settingsRegion !== 'content'
    ) return
    const page = activePage
    void tick().then(() => requestAnimationFrame(() => {
      if (open && activePage === page && settingsRegion === 'content') {
        selectSettingsControl(selectedSettingsControlIndex, false)
      }
    }))
  })

  $effect(() => {
    if (!open) return
    dialogGuardOpen()
    return () => dialogGuardClose()
  })

  $effect(() => {
    if (getEnhancedKeyboardNavigation()) return
    stopObservingSelectLifecycle()
    clearSettingsKeyboardSelection()
  })

  $effect(() => {
    if (!open || draft.loading || !draft.dirty || autoSaveBlocked) return
    void queueAutoSave()
  })

  async function runAutoSaveLoop() {
    while (open && !draft.loading && draft.dirty && !autoSaveBlocked) {
      const savedNativeTitleBar = draft.nativeTitleBar
      const nativeTitleBarChanged = savedNativeTitleBar !== draft.originalNativeTitleBar
      try {
        await draft.saveAll()
        if (nativeTitleBarChanged) {
          draft.originalNativeTitleBar = savedNativeTitleBar
          showRestartDialog = true
        }
        scheduleSettingsControlSelection()
      } catch (error) {
        console.error('Failed to auto-save settings:', error)
        addToast({ type: 'error', message: $_('toast.failedToSaveSettings') })
        autoSaveBlocked = true
        try {
          await draft.load()
          autoSaveBlocked = false
        } catch (loadError) {
          console.error('Failed to reload settings after auto-save error:', loadError)
          addToast({ type: 'error', message: $_('toast.failedToLoadSettings') })
        }
      }
    }
  }

  function queueAutoSave(): Promise<void> {
    if (!autoSavePromise) {
      autoSavePromise = runAutoSaveLoop().finally(() => { autoSavePromise = null })
    }
    return autoSavePromise
  }

  async function close() {
    if (closeInProgress) return
    closeInProgress = true
    try {
      if (draft.dirty && !autoSaveBlocked) await queueAutoSave()
      else if (autoSavePromise) await autoSavePromise
      open = false
      onClose?.()
    } finally {
      closeInProgress = false
    }
  }

  function handleOpenChange(value: boolean) {
    if (value) {
      open = true
      return
    }
    if (closeInProgress) return
    open = true
    void close()
  }
  function openBackupActivityLog() { selectNavigationPage('activity', 'backup') }
  function restoreActivityLogPositionAfterLoad(hasMore: boolean) {
    void tick().then(() => requestAnimationFrame(() => {
      if (!open || activePage !== 'activity' || settingsRegion !== 'content') return
      if (hasMore) {
        const loadMore = getSettingsControls().find((control) => (
          control.dataset.settingsControlId === 'activity-load-more'
        ))
        if (loadMore) {
          selectSettingsControlElement(loadMore)
          return
        }
      }

      const closeAction = getSettingsControls().find((control) => (
        control.dataset.settingsControlId === 'settings-close'
      ))
      if (!closeAction) return
      contentRegionEl?.focus({ preventScroll: true })
      selectSettingsControlForTarget(closeAction)
    }))
  }

  function selectNavigationPage(page: SettingsPage, initialActivityType = '') {
    if (page === 'activity') activityInitialType = initialActivityType
    if (activePage !== page) selectedSettingsControlIndex = 0
    selectedNavigationPage = page
    activePage = page
    if (settingsRegion === 'content') scheduleSettingsControlSelection(true, true)
  }

  function keepDialogFromTakingPointerFocus(event: PointerEvent) {
    if (event.button !== 0 || !(event.target instanceof Element)) return
    const interactive = event.target.closest('button, a, input, textarea, select, [role="button"], [role="tab"], [role="option"], [contenteditable="true"]')
    if (!interactive) event.preventDefault()
  }

  function focusSettingsRegion(region: 'navigation' | 'content') {
    stopObservingSelectLifecycle()
    settingsContentMode = 'browse'
    settingsRegion = region
    const target = region === 'navigation' ? navigationRegionEl : contentRegionEl
    target?.focus({ preventScroll: true })
    if (region === 'content') scheduleSettingsControlSelection()
  }

  function isAvailableSettingsControl(control: HTMLElement): boolean {
    return !control.hidden
      && !control.matches(':disabled')
      && control.getAttribute('aria-disabled') !== 'true'
      && control.getAttribute('aria-hidden') !== 'true'
      && !control.closest('[hidden], [aria-hidden="true"]')
  }

  function getSettingsControls(): HTMLElement[] {
    if (!contentPanelEl) return []
    const controls = Array.from(contentPanelEl.querySelectorAll<HTMLElement>(SETTINGS_CONTROL_SELECTOR))
      .filter(isAvailableSettingsControl)
    const orderGroups = new Map<HTMLElement, Array<{ control: HTMLElement; index: number; order: number }>>()
    controls.forEach((control, index) => {
      const group = control.closest<HTMLElement>('[data-settings-keyboard-order-group]')
      const order = Number(control.dataset.settingsKeyboardOrder)
      if (!group || !Number.isFinite(order)) return
      const entries = orderGroups.get(group) ?? []
      entries.push({ control, index, order })
      orderGroups.set(group, entries)
    })

    for (const entries of orderGroups.values()) {
      const slots = entries.map(({ index }) => index).sort((left, right) => left - right)
      const ordered = [...entries].sort((left, right) => left.order - right.order)
      slots.forEach((slot, index) => { controls[slot] = ordered[index].control })
    }
    if (closeButtonEl && isAvailableSettingsControl(closeButtonEl)) controls.push(closeButtonEl)
    return controls
  }

  function getSettingsContentItems(): SettingsContentItem[] {
    return getSettingsControls().map((element): SettingsContentItem => ({ kind: 'control', element }))
  }

  function getSettingsHorizontalGroupControls(
    group: HTMLElement,
    includeUnavailable = false,
  ): HTMLElement[] {
    const controls = Array.from(group.querySelectorAll<HTMLElement>(
      '[data-settings-horizontal-action]',
    ))
    return includeUnavailable ? controls : controls.filter(isAvailableSettingsControl)
  }

  function getSettingsHorizontalGroups(): HTMLElement[] {
    if (!contentPanelEl) return []
    return Array.from(contentPanelEl.querySelectorAll<HTMLElement>(
      '[data-settings-horizontal-group]',
    )).filter((group) => getSettingsHorizontalGroupControls(group).length > 0)
  }

  function settingsHorizontalGroupForControl(control: HTMLElement): HTMLElement | null {
    const group = control.closest<HTMLElement>('[data-settings-horizontal-group]')
    return group && contentPanelEl?.contains(group) ? group : null
  }

  function selectSettingsControlElement(control: HTMLElement) {
    const itemIndex = getSettingsContentItems().findIndex((item) => (
      item.kind === 'control' && item.element === control
    ))
    if (itemIndex < 0) return
    contentRegionEl?.focus({ preventScroll: true })
    selectSettingsControl(itemIndex)
  }

  function selectHorizontalGroupControl(control: HTMLElement, direction: -1 | 1) {
    const group = settingsHorizontalGroupForControl(control)
    if (!group) return
    const controls = getSettingsHorizontalGroupControls(group)
    const currentIndex = controls.indexOf(control)
    const nextIndex = nextRovingIndex(
      direction === -1 ? 'ArrowUp' : 'ArrowDown',
      currentIndex,
      controls.length,
      true,
    )
    if (nextIndex >= 0) selectSettingsControlElement(controls[nextIndex])
  }

  function closestAvailableHorizontalGroupControl(
    sourceControl: HTMLElement,
    targetGroup: HTMLElement,
  ): HTMLElement | null {
    const availableControls = getSettingsHorizontalGroupControls(targetGroup)
    if (availableControls.length === 0) return null

    const sourceAction = sourceControl.dataset.settingsHorizontalAction
    const matchingAction = availableControls.find((control) => (
      control.dataset.settingsHorizontalAction === sourceAction
    ))
    if (matchingAction) return matchingAction

    const sourceGroup = settingsHorizontalGroupForControl(sourceControl)
    const sourceSlot = sourceGroup
      ? getSettingsHorizontalGroupControls(sourceGroup, true).indexOf(sourceControl)
      : 0
    const targetControls = getSettingsHorizontalGroupControls(targetGroup, true)
    return availableControls.reduce((closest, candidate) => (
      Math.abs(targetControls.indexOf(candidate) - sourceSlot)
        < Math.abs(targetControls.indexOf(closest) - sourceSlot)
        ? candidate
        : closest
    ))
  }

  function selectAdjacentHorizontalGroup(control: HTMLElement, direction: -1 | 1) {
    const currentGroup = settingsHorizontalGroupForControl(control)
    if (!currentGroup) return
    const groups = getSettingsHorizontalGroups()
    const currentIndex = groups.indexOf(currentGroup)
    const nextIndex = nextRovingIndex(
      direction === -1 ? 'ArrowUp' : 'ArrowDown',
      currentIndex,
      groups.length,
      true,
    )
    if (nextIndex < 0) return
    const target = closestAvailableHorizontalGroupControl(control, groups[nextIndex])
    if (target) selectSettingsControlElement(target)
  }

  function selectOutsideHorizontalGroup(group: HTMLElement, direction: -1 | 1) {
    const items = getSettingsContentItems()
    const groupIndices = items.flatMap((item, index) => (
      item.kind === 'control' && group.contains(item.element) ? [index] : []
    ))
    if (groupIndices.length === 0) return

    const boundaryIndex = direction === -1
      ? Math.min(...groupIndices)
      : Math.max(...groupIndices)
    const nextIndex = nextRovingIndex(
      direction === -1 ? 'ArrowUp' : 'ArrowDown',
      boundaryIndex,
      items.length,
      true,
    )
    if (nextIndex < 0) return
    contentRegionEl?.focus({ preventScroll: true })
    selectSettingsControl(nextIndex)
  }

  function selectExplicitHorizontalGroupTarget(group: HTMLElement, direction: -1 | 1): boolean {
    const targetID = direction === -1
      ? group.dataset.settingsArrowUpTarget
      : group.dataset.settingsArrowDownTarget
    if (!targetID) return false

    const target = getSettingsControls().find((control) => (
      control.dataset.settingsControlId === targetID
    ))
    if (target) {
      selectSettingsControlElement(target)
      return true
    }

    const fallbackActionID = direction === -1
      ? group.dataset.settingsArrowUpFallback
      : group.dataset.settingsArrowDownFallback
    if (!fallbackActionID) return false
    const fallbackAction = getSettingsControls().find((control) => (
      control.dataset.settingsControlId === fallbackActionID
    ))
    if (!fallbackAction) return false
    contentRegionEl?.focus({ preventScroll: true })
    selectSettingsControlForTarget(fallbackAction)
    return true
  }

  function restoreSettingsHorizontalControlAfterRender(
    context: string,
    action: 'move-up' | 'move-down',
  ) {
    void tick().then(() => requestAnimationFrame(() => {
      if (!open || activePage !== 'accounts' || settingsRegion !== 'content') return
      const group = getSettingsHorizontalGroups().find((candidate) => (
        candidate.dataset.settingsHorizontalContext === context
      ))
      if (!group) return

      const controls = getSettingsHorizontalGroupControls(group, true)
      const targetIndex = resolveHorizontalActionIndex(
        controls.map((control) => ({
          action: control.dataset.settingsHorizontalAction ?? '',
          available: isAvailableSettingsControl(control),
        })),
        action,
      )
      const target = controls[targetIndex]
      if (!target) return

      if (getEnhancedKeyboardNavigation()) {
        settingsContentMode = 'browse'
        selectSettingsControlElement(target)
      } else {
        target.focus({ preventScroll: true })
      }
    }))
  }

  function clearSettingsKeyboardSelection() {
    contentRegionEl?.querySelectorAll<HTMLElement>('[data-settings-keyboard-selected]')
      .forEach((element) => { delete element.dataset.settingsKeyboardSelected })
  }

  function selectSettingsControl(index: number, scroll = true) {
    const settingsContentItems = getSettingsContentItems()
    clearSettingsKeyboardSelection()
    if (settingsContentItems.length === 0) {
      selectedSettingsControlIndex = -1
      return
    }

    selectedSettingsControlIndex = Math.max(0, Math.min(index, settingsContentItems.length - 1))
    const selectedItem = settingsContentItems[selectedSettingsControlIndex]
    selectedItem.element.dataset.settingsKeyboardSelected = 'true'
    if (scroll) selectedItem.element.scrollIntoView({ block: 'nearest' })
  }

  function scheduleSettingsControlSelection(reset = false, restoreFocus = false) {
    const page = activePage
    void tick().then(() => requestAnimationFrame(() => {
      if (!open || activePage !== page || settingsRegion !== 'content') return
      if (restoreFocus) contentRegionEl?.focus({ preventScroll: true })
      const preferredIndex = reset
        ? getSettingsContentItems().findIndex((item) => (
          item.kind === 'control'
          && item.element.dataset.settingsInitialSelection === 'true'
        ))
        : -1
      selectSettingsControl(
        preferredIndex >= 0 ? preferredIndex : reset ? 0 : selectedSettingsControlIndex,
        false,
      )
    }))
  }

  function settingsControlForTarget(target: EventTarget | null): HTMLElement | null {
    if (!(target instanceof Element)) return null
    const control = target.closest<HTMLElement>(SETTINGS_CONTROL_SELECTOR)
    return control && (contentPanelEl?.contains(control) || control === closeButtonEl) ? control : null
  }

  function isNativeSettingsControlTarget(target: EventTarget | null): boolean {
    return Boolean(settingsControlForTarget(target))
  }

  function isSettingsSelectTrigger(control: HTMLElement): boolean {
    return control.matches('[data-keyboard-select-trigger="true"]')
  }

  function isSettingsMenuTrigger(control: HTMLElement): boolean {
    return control.matches('[data-keyboard-menu-trigger="true"]')
  }

  function selectSettingsControlForTarget(target: EventTarget | null, showSelection = true) {
    const control = settingsControlForTarget(target)
    if (control) {
      const index = getSettingsControls().indexOf(control)
      if (index >= 0) {
        selectedSettingsControlIndex = index
        if (showSelection) selectSettingsControl(index, false)
        else clearSettingsKeyboardSelection()
      }
      return
    }

  }

  function stopObservingSelectLifecycle() {
    selectStateObserver?.disconnect()
    selectStateObserver = null
  }

  function isOpenSelect(control: HTMLElement): boolean {
    return control.getAttribute('aria-expanded') === 'true' || control.dataset.state === 'open'
  }

  function finishSettingsInput() {
    stopObservingSelectLifecycle()
    settingsContentMode = 'browse'
    requestAnimationFrame(() => {
      if (!open) return
      const nestedDialog = [...document.querySelectorAll<HTMLElement>(
        '[role="dialog"][data-state="open"], [role="alertdialog"][data-state="open"]',
      )].find((dialog) => !dialog.contains(contentRegionEl))
      if (nestedDialog) return
      contentRegionEl?.focus({ preventScroll: true })
      selectSettingsControl(selectedSettingsControlIndex, false)
    })
  }

  function observeSelectLifecycle(control: HTMLElement) {
    stopObservingSelectLifecycle()
    let sawOpen = isOpenSelect(control)
    selectStateObserver = new MutationObserver(() => {
      if (isOpenSelect(control)) {
        sawOpen = true
        return
      }
      if (sawOpen) finishSettingsInput()
    })
    selectStateObserver.observe(control, {
      attributes: true,
      attributeFilter: ['aria-expanded', 'data-state'],
    })
  }

  function beginSettingsInput(
    control: HTMLElement,
    activate = true,
    activationKey: 'Enter' | ' ' = 'Enter',
  ) {
    settingsContentMode = 'input'
    const isPopupTrigger = isSettingsSelectTrigger(control) || isSettingsMenuTrigger(control)
    if (isPopupTrigger) observeSelectLifecycle(control)
    if (!activate) {
      clearSettingsKeyboardSelection()
      return
    }
    control.focus({ preventScroll: true })
    clearSettingsKeyboardSelection()
    if (isPopupTrigger) {
      control.dispatchEvent(new KeyboardEvent('keydown', {
        key: activationKey,
        code: activationKey === ' ' ? 'Space' : 'Enter',
        bubbles: true,
        cancelable: true,
        composed: true,
      }))
      return
    }
    control.click()
  }

  function activateSelectedSettingsControl(activationKey: 'Enter' | ' ') {
    const selectedItem = getSettingsContentItems()[selectedSettingsControlIndex]
    if (!selectedItem) return
    const control = selectedItem.element
    if (isSettingsSelectTrigger(control) || isSettingsMenuTrigger(control) || isInputElement(control)) {
      beginSettingsInput(control, true, activationKey)
      return
    }
    control.focus({ preventScroll: true })
    control.click()
  }

  function handleContentFocusIn(event: FocusEvent) {
    settingsRegion = 'content'
    if (!getEnhancedKeyboardNavigation()) {
      clearSettingsKeyboardSelection()
      return
    }
    selectSettingsControlForTarget(event.target, settingsContentMode === 'browse')
    if (event.target === contentRegionEl) selectSettingsControl(selectedSettingsControlIndex, false)
  }

  function handleContentMouseDown(event: MouseEvent) {
    settingsRegion = 'content'
    if (!getEnhancedKeyboardNavigation()) {
      clearSettingsKeyboardSelection()
      return
    }
    const control = settingsControlForTarget(event.target)
    if (control && isInputElement(control)) {
      beginSettingsInput(control, false)
    } else {
      stopObservingSelectLifecycle()
      settingsContentMode = 'browse'
    }
    selectSettingsControlForTarget(event.target, settingsContentMode === 'browse')
    if (!isNativeSettingsControlTarget(event.target)) {
      requestAnimationFrame(() => contentRegionEl?.focus({ preventScroll: true }))
    }
  }

  function handleOpenAutoFocus(event: Event) {
    if (!getEnhancedKeyboardNavigation()) return
    event.preventDefault()
    void tick().then(() => requestAnimationFrame(() => focusSettingsRegion('navigation')))
  }

  function handleSettingsKeydown(event: KeyboardEvent) {
    if (
      !getEnhancedKeyboardNavigation()
      || event.defaultPrevented
      || event.isComposing
      || event.keyCode === 229
      || showRestartDialog
    ) return
    if (event.key === 'F10' && event.shiftKey && !event.ctrlKey && !event.metaKey && !event.altKey) {
      event.preventDefault()
      event.stopPropagation()
      keyboardActionMenu.showForRoot(
        settingsRegion === 'navigation' ? navigationRegionEl : contentRegionEl,
      )
      return
    }
    if (event.key === 'Escape' && settingsContentMode === 'input') {
      const activeControl = settingsControlForTarget(event.target)
      if (
        activeControl
        && (isSettingsSelectTrigger(activeControl) || isSettingsMenuTrigger(activeControl))
        && isOpenSelect(activeControl)
      ) return
      event.preventDefault()
      event.stopPropagation()
      ;(event.target as HTMLElement | null)?.blur?.()
      finishSettingsInput()
      return
    }
    if (event.key === 'Escape') {
      event.preventDefault()
      event.stopPropagation()
      void close()
      return
    }
    if (event.key === 'Tab' && settingsContentMode === 'browse') {
      event.preventDefault()
      event.stopPropagation()
      focusSettingsRegion(settingsRegion === 'navigation' ? 'content' : 'navigation')
      return
    }
    if (settingsRegion === 'navigation') {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault()
        event.stopPropagation()
        selectNavigationPage(selectedNavigationPage)
        return
      }
      if (!['ArrowUp', 'ArrowDown', 'Home', 'End'].includes(event.key)) return
      event.preventDefault()
      event.stopPropagation()
      settingsNavigationInputMode = 'keyboard'
      const currentIndex = navigation.findIndex((item) => item.id === selectedNavigationPage)
      const nextIndex = nextRovingIndex(event.key as RovingNavigationKey, currentIndex, navigation.length, true)
      if (nextIndex >= 0) selectNavigationPage(navigation[nextIndex].id)
      return
    }

    if (settingsContentMode === 'input') return
    const selectedItem = getSettingsContentItems()[selectedSettingsControlIndex]
    const selectedHorizontalGroup = selectedItem?.kind === 'control'
      ? settingsHorizontalGroupForControl(selectedItem.element)
      : null
    if (
      selectedHorizontalGroup
      && ['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(event.key)
    ) {
      event.preventDefault()
      event.stopPropagation()
      if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
        selectHorizontalGroupControl(selectedItem.element, event.key === 'ArrowLeft' ? -1 : 1)
      } else if (selectedHorizontalGroup.hasAttribute('data-settings-horizontal-arrows-only')) {
        const direction = event.key === 'ArrowUp' ? -1 : 1
        if (!selectExplicitHorizontalGroupTarget(selectedHorizontalGroup, direction)) {
          selectOutsideHorizontalGroup(selectedHorizontalGroup, direction)
        }
      } else if (event.key === 'ArrowUp' || event.key === 'ArrowDown') {
        selectAdjacentHorizontalGroup(selectedItem.element, event.key === 'ArrowUp' ? -1 : 1)
      }
      return
    }
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault()
      event.stopPropagation()
      activateSelectedSettingsControl(event.key)
      return
    }
    if (!['ArrowUp', 'ArrowDown', 'Home', 'End'].includes(event.key)) return
    event.preventDefault()
    event.stopPropagation()
    const settingsContentItems = getSettingsContentItems()
    const nextIndex = nextRovingIndex(
      event.key as RovingNavigationKey,
      selectedSettingsControlIndex,
      settingsContentItems.length, true,
    )
    if (nextIndex >= 0) {
      contentRegionEl?.focus({ preventScroll: true })
      selectSettingsControl(nextIndex)
    }
  }
</script>

<Dialog.Root bind:open onOpenChange={handleOpenChange}>
  <Dialog.Content class="h-[min(680px,88vh)] max-h-[88vh] w-[min(980px,94vw)] max-w-none gap-0 overflow-hidden p-0 !outline-none focus:!outline-none focus-visible:!outline-none focus:ring-0 focus-visible:ring-0 [&>button]:hidden" onOpenAutoFocus={handleOpenAutoFocus} preventCloseAutoFocus onpointerdown={keepDialogFromTakingPointerFocus} onInteractOutside={(event) => event.preventDefault()}>
    <Dialog.Title class="sr-only">{$_('settings.title')}</Dialog.Title>
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div class="grid min-h-0 flex-1 grid-cols-[210px_minmax(0,1fr)]" onkeydowncapture={handleSettingsKeydown}>
      <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
      <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
      <aside
        bind:this={navigationRegionEl}
        tabindex="0"
        data-settings-region="navigation"
        data-region-active={getEnhancedKeyboardNavigation() && settingsRegion === 'navigation'}
        class="keyboard-region flex min-h-0 flex-col border-r border-border bg-muted/35 px-3 py-6 outline-none"
        onfocusin={() => {
          stopObservingSelectLifecycle()
          settingsContentMode = 'browse'
          settingsRegion = 'navigation'
        }}
        onmousedown={() => {
          stopObservingSelectLifecycle()
          settingsContentMode = 'browse'
          settingsRegion = 'navigation'
        }}
        onpointermove={() => { settingsNavigationInputMode = 'pointer' }}
      >
        <h1 class="mb-6 flex h-5 items-center px-2 text-lg font-semibold leading-5">{$_('settings.title')}</h1>
        <nav aria-label={$_('settings.title')}>
          <div class="space-y-1" role="tablist" aria-orientation="vertical">
            {#each navigation as item (item.id)}
              <button
                type="button"
                id={`settings-tab-${item.id}`}
                data-settings-page={item.id}
                role="tab"
                tabindex="-1"
                aria-selected={activePage === item.id}
                aria-controls={`settings-panel-${item.id}`}
                class="flex h-9 w-full items-center gap-2.5 rounded-lg px-3 text-left text-sm font-medium transition-colors focus:outline-none {activePage === item.id
                  ? 'bg-background/70 text-primary'
                  : selectedNavigationPage === item.id
                    ? 'bg-background/70 text-primary'
                    : settingsNavigationInputMode === 'pointer'
                      ? 'text-muted-foreground hover:bg-background/70 hover:text-foreground'
                      : 'text-muted-foreground'}"
                onclick={() => selectNavigationPage(item.id)}
              >
                <Icon icon={item.icon} class="h-[18px] w-[18px] shrink-0" /><span class="truncate">{item.label}</span>
              </button>
            {/each}
          </div>
        </nav>
        <div class="mt-auto px-1 pt-4 text-center text-xs text-muted-foreground">
          <UpdateAction compact />
          <div class="mt-1">{$_('settingsAbout.version', { values: { version: appInfo?.version ?? '—' } })}</div>
        </div>
      </aside>

      <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div
        bind:this={contentRegionEl}
        tabindex="0"
        data-settings-region="content"
        data-region-active={getEnhancedKeyboardNavigation() && settingsRegion === 'content'}
        class="keyboard-region relative flex min-h-0 min-w-0 flex-col bg-background outline-none"
        onfocusin={handleContentFocusIn}
        onmousedown={handleContentMouseDown}
      >
        <div
          bind:this={contentPanelEl}
          id={`settings-panel-${activePage}`}
          role="tabpanel"
          aria-labelledby={`settings-tab-${activePage}`}
          class="relative min-h-0 flex-1 px-7 py-6 scrollbar-thin {activePage === 'activity' || activePage === 'about' ? 'overflow-hidden' : 'overflow-y-auto'}"
        >
          {#if activePage === 'about'}<AboutTab {appInfo} loading={appInfoLoading} />
          {:else if draft.loading}
            <div class="flex h-full items-center justify-center"><Icon icon="mdi:loading" class="h-6 w-6 animate-spin text-muted-foreground" /></div>
          {:else if activePage === 'general'}<GeneralSettingsPage {draft} />
          {:else if activePage === 'appearance'}<AppearanceSettingsPage {draft} />
          {:else if activePage === 'mail'}<MailSettingsPage {draft} />
          {:else if activePage === 'accounts'}<AccountsSettingsPage onAccountOrderChanged={restoreSettingsHorizontalControlAfterRender} />
          {:else if activePage === 'backup'}<BackupSettingsPage {draft} onOpenActivityLog={openBackupActivityLog} />
          {:else}<ActivityLogPage initialType={activityInitialType} onLoadMoreFinished={restoreActivityLogPositionAfterLoad} />{/if}
        </div>
        {#if draft.saving}
          <div data-settings-autosave-status aria-live="polite" class="pointer-events-none absolute right-14 top-5 flex h-7 items-center gap-1.5 rounded-md bg-background/90 px-2 text-xs text-muted-foreground">
            <Icon icon="mdi:loading" class="h-3.5 w-3.5 animate-spin" />
            <span>{$_('settings.saving')}</span>
          </div>
        {/if}
        <button
          bind:this={closeButtonEl}
          type="button"
          data-settings-close
          data-settings-control-id="settings-close"
          aria-label={$_('common.close')}
          title={$_('common.close')}
          class="absolute right-5 top-5 flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/60"
          onclick={() => void close()}
        >
          <Icon icon="mdi:close" class="h-4 w-4" />
        </button>
      </div>
    </div>
  </Dialog.Content>
</Dialog.Root>

<ConfirmDialog bind:open={showRestartDialog} title={$_('settingsGeneral.restartRequired')} description={$_('settingsGeneral.restartRequiredDescription')} confirmLabel={$_('settingsGeneral.quitNow')} cancelLabel={$_('settingsGeneral.restartLater')} onConfirm={() => QuitApp()} onCancel={() => showRestartDialog = false} />

<style>
  :global([data-settings-keyboard-selected='true']) {
    border-radius: 0.625rem;
    outline: 2px solid hsl(var(--primary) / 0.7);
    outline-offset: 3px;
  }

  /* An open Select already owns the visible blue ring. During pointerdown,
     suppress the Settings browse outline so the two indicators never stack. */
  :global([data-settings-keyboard-selected='true'][data-keyboard-select-trigger='true'][data-state='open']) {
    outline: none;
  }

  /* Document-style links use a compact background and underline instead of a
     large rectangular ring. Avoid a left inset marker: rounded links render it
     as a distracting crescent. */
  :global([data-settings-focus-style='link'][data-settings-keyboard-selected='true']) {
    background-color: hsl(var(--primary) / 0.1);
    outline: none;
    text-decoration-line: underline;
    text-decoration-thickness: 1px;
    text-underline-offset: 3px;
  }

  :global([data-settings-contrast-selection][data-settings-keyboard-selected='true']) {
    outline-offset: 2px;
    box-shadow: 0 0 0 2px hsl(var(--background));
  }

</style>
