// @ts-ignore - generated by Wails
import {
  GetAccentBarUnread,
  GetAlwaysLoadImages,
  GetAutostart,
  GetBackupSettings,
  GetComposerFormat,
  GetDarkMailContent,
  GetDeveloperMode,
  GetLanguage,
  GetMarkAsReadDelay,
  GetMenuBarIcon,
  GetMessageListDensity,
  GetNativeTitleBar,
  GetReadReceiptResponsePolicy,
  GetRunBackground,
  GetStartHidden,
  GetThemeMode,
  SetAccentBarUnread,
  SetAlwaysLoadImages,
  SetAutostart,
  SetBackupSettings,
  SetComposerFormat,
  SetDarkMailContent,
  SetDeveloperMode,
  SetLanguage,
  SetMarkAsReadDelay,
  SetMenuBarIcon,
  SetMessageListDensity,
  SetNativeTitleBar,
  SetReadReceiptResponsePolicy,
  SetRunBackground,
  SetStartHidden,
  SetThemeMode,
} from '../../../../wailsjs/go/app/App.js'
import {
  setAccentBarUnread as updateAccentBarUnreadStore,
  setAlwaysLoadImages as updateAlwaysLoadImagesStore,
  setComposerFormat as updateComposerFormatStore,
  setDarkMailContent as updateDarkMailContentStore,
  setDeveloperMode as updateDeveloperModeStore,
  setLanguage as updateLanguageStore,
  setMessageListDensity as updateDensityStore,
  setThemeMode as updateThemeStore,
  type ComposerFormat,
  type MessageListDensity,
  type ThemeMode,
} from '$lib/stores/settings.svelte'
import { rememberBackupDirectory } from '$lib/utils/backup-directory-history'

export type BackupScope = 'all' | 'selected'

type Snapshot = {
  readReceiptResponsePolicy: string
  markAsReadDelaySeconds: number
  messageListDensity: string
  themeMode: string
  runBackground: boolean
  startHidden: boolean
  autostart: boolean
  language: string
  composerFormat: string
  nativeTitleBar: boolean
  alwaysLoadImages: boolean
  darkMailContent: boolean
  accentBarUnread: boolean
  menuBarIcon: boolean
  developerMode: boolean
}

export class SettingsDraft {
  readReceiptResponsePolicy = $state('ask')
  markAsReadDelaySeconds = $state(1)
  messageListDensity = $state('standard')
  themeMode = $state('pop-dark')
  runBackground = $state(false)
  startHidden = $state(false)
  autostart = $state(false)
  language = $state('')
  composerFormat = $state('rich')
  nativeTitleBar = $state(false)
  alwaysLoadImages = $state(false)
  darkMailContent = $state(false)
  accentBarUnread = $state(false)
  menuBarIcon = $state(false)
  developerMode = $state(false)
  backupDirectory = $state('')
  backupScope = $state<BackupScope>('all')
  backupSelectedAccountIds = $state<string[]>([])
  loading = $state(false)
  saving = $state(false)
  originalNativeTitleBar = false
  private original = $state('')
  private originalBackup = $state('')

  get dirty(): boolean {
    return this.original !== JSON.stringify(this.snapshot()) || this.backupDirty
  }

  get backupDirty(): boolean {
    return this.originalBackup !== JSON.stringify(this.backupSnapshot())
  }

  async load(): Promise<void> {
    this.loading = true
    try {
      const [policy, delayMs, density, theme, runBg, startHid, autoSt, lang, compFmt, nativeTB, alwaysImages, darkMail, accentBar, menuBar, devMode, backup] = await Promise.all([
        GetReadReceiptResponsePolicy(), GetMarkAsReadDelay(), GetMessageListDensity(), GetThemeMode(),
        GetRunBackground(), GetStartHidden(), GetAutostart(), GetLanguage(), GetComposerFormat(),
        GetNativeTitleBar(), GetAlwaysLoadImages(), GetDarkMailContent(), GetAccentBarUnread(),
        GetMenuBarIcon(), GetDeveloperMode(), GetBackupSettings(),
      ])
      this.readReceiptResponsePolicy = policy
      this.markAsReadDelaySeconds = delayMs < 0 ? -1 : delayMs / 1000
      this.messageListDensity = density
      this.themeMode = theme === 'pop-dark' || theme === 'light-blue' ? theme : 'pop-dark'
      this.runBackground = Boolean(runBg)
      this.startHidden = Boolean(startHid)
      this.autostart = Boolean(autoSt)
      this.language = lang
      this.composerFormat = compFmt || 'rich'
      this.nativeTitleBar = Boolean(nativeTB)
      this.alwaysLoadImages = Boolean(alwaysImages)
      this.darkMailContent = Boolean(darkMail)
      this.accentBarUnread = Boolean(accentBar)
      this.menuBarIcon = Boolean(menuBar)
      this.developerMode = Boolean(devMode)
      this.backupDirectory = backup?.directory ?? ''
      this.backupScope = backup?.scope === 'selected' ? 'selected' : 'all'
      this.backupSelectedAccountIds = backup?.selectedAccountIds ?? []
      this.originalNativeTitleBar = this.nativeTitleBar
      this.capture()
    } finally {
      this.loading = false
    }
  }

  async saveAll(): Promise<void> {
    this.saving = true
    try {
      const delayMs = this.markAsReadDelaySeconds < 0 ? -1 : Math.round(this.markAsReadDelaySeconds * 1000)
      const effectiveRunBackground = this.menuBarIcon ? true : this.runBackground
      await SetReadReceiptResponsePolicy(this.readReceiptResponsePolicy)
      await SetMarkAsReadDelay(delayMs)
      await SetMessageListDensity(this.messageListDensity)
      await SetThemeMode(this.themeMode)
      await SetRunBackground(effectiveRunBackground)
      await SetStartHidden(this.startHidden)
      await SetAutostart(this.autostart)
      if (this.language) await SetLanguage(this.language)
      await SetComposerFormat(this.composerFormat)
      await SetNativeTitleBar(this.nativeTitleBar)
      await SetAlwaysLoadImages(this.alwaysLoadImages)
      await SetDarkMailContent(this.darkMailContent)
      await SetAccentBarUnread(this.accentBarUnread)
      await SetMenuBarIcon(this.menuBarIcon)
      await SetDeveloperMode(this.developerMode)
      if (this.backupDirty) await this.saveBackup()

      this.runBackground = effectiveRunBackground
      updateDensityStore(this.messageListDensity as MessageListDensity)
      updateThemeStore(this.themeMode as ThemeMode)
      if (this.language) updateLanguageStore(this.language)
      updateComposerFormatStore(this.composerFormat as ComposerFormat)
      updateAlwaysLoadImagesStore(this.alwaysLoadImages)
      updateDarkMailContentStore(this.darkMailContent)
      updateAccentBarUnreadStore(this.accentBarUnread)
      updateDeveloperModeStore(this.developerMode)
      this.capture()
    } finally {
      this.saving = false
    }
  }

  async saveBackup(): Promise<void> {
    await SetBackupSettings({
      directory: this.backupDirectory.trim(),
      scope: this.backupScope,
      selectedAccountIds: this.backupSelectedAccountIds,
    })
    if (this.backupDirectory.trim()) rememberBackupDirectory(this.backupDirectory.trim())
    this.originalBackup = JSON.stringify(this.backupSnapshot())
  }

  private capture(): void {
    this.original = JSON.stringify(this.snapshot())
    this.originalBackup = JSON.stringify(this.backupSnapshot())
  }

  private backupSnapshot() {
    return {
      directory: this.backupDirectory.trim(),
      scope: this.backupScope,
      selectedAccountIds: [...this.backupSelectedAccountIds].sort(),
    }
  }

  private snapshot(): Snapshot {
    return {
      readReceiptResponsePolicy: this.readReceiptResponsePolicy,
      markAsReadDelaySeconds: this.markAsReadDelaySeconds,
      messageListDensity: this.messageListDensity,
      themeMode: this.themeMode,
      runBackground: this.runBackground,
      startHidden: this.startHidden,
      autostart: this.autostart,
      language: this.language,
      composerFormat: this.composerFormat,
      nativeTitleBar: this.nativeTitleBar,
      alwaysLoadImages: this.alwaysLoadImages,
      darkMailContent: this.darkMailContent,
      accentBarUnread: this.accentBarUnread,
      menuBarIcon: this.menuBarIcon,
      developerMode: this.developerMode,
    }
  }
}
