<script lang="ts">
  import Icon from '@iconify/svelte'
  import * as Dialog from '$lib/components/ui/dialog'
  import { Button } from '$lib/components/ui/button'
  import ConfirmDialog from '$lib/components/ui/confirm-dialog/ConfirmDialog.svelte'
  import { addToast } from '$lib/stores/toast'
  import { dialogGuardClose, dialogGuardOpen } from '$lib/stores/dialogGuard'
  import { _ } from '$lib/i18n'
  // @ts-ignore - generated by Wails
  import { GetAppInfo, QuitApp } from '../../../../wailsjs/go/app/App.js'
  import type { app } from '../../../../wailsjs/go/models'
  import { SettingsDraft } from './settingsDraft.svelte'
  import GeneralSettingsPage from './pages/GeneralSettingsPage.svelte'
  import AppearanceSettingsPage from './pages/AppearanceSettingsPage.svelte'
  import MailSettingsPage from './pages/MailSettingsPage.svelte'
  import AccountsSettingsPage from './pages/AccountsSettingsPage.svelte'
  import BackupSettingsPage from './backup/BackupSettingsPage.svelte'
  import ActivityLogPage from './activity/ActivityLogPage.svelte'
  import AboutTab from './AboutTab.svelte'

  type SettingsPage = 'general' | 'appearance' | 'mail' | 'accounts' | 'backup' | 'activity' | 'about'
  interface NavigationItem { id: SettingsPage; icon: string; label: string }
  interface Props { open?: boolean; activePage?: SettingsPage; onClose?: () => void }
  let { open = $bindable(false), activePage = $bindable('general'), onClose }: Props = $props()
  const draft = new SettingsDraft()
  let appInfo = $state<app.AppInfo | null>(null)
  let appInfoLoading = $state(false)
  let showRestartDialog = $state(false)
  let loadSequence = 0

  const navigation: NavigationItem[] = $derived([
    { id: 'general', icon: 'lucide:settings-2', label: $_('settings.general') },
    { id: 'appearance', icon: 'lucide:palette', label: $_('settings.appearance') },
    { id: 'mail', icon: 'lucide:mail', label: $_('settings.mail') },
    { id: 'accounts', icon: 'lucide:mails', label: $_('settings.accounts') },
    { id: 'backup', icon: 'lucide:archive', label: $_('settings.backup') },
    { id: 'activity', icon: 'lucide:history', label: $_('activityLog.title') },
    { id: 'about', icon: 'lucide:info', label: $_('settings.about') },
  ])

  $effect(() => {
    if (!open) return
    const sequence = ++loadSequence
    appInfoLoading = true
    draft.load().catch((error) => {
      if (sequence !== loadSequence) return
      console.error('Failed to load settings:', error)
      addToast({ type: 'error', message: $_('toast.failedToLoadSettings') })
    })
    GetAppInfo().then((info) => {
      if (sequence === loadSequence) appInfo = info
    }).catch((error) => {
      if (sequence !== loadSequence) return
      appInfo = null
      console.error('Failed to load app info:', error)
    }).finally(() => {
      if (sequence === loadSequence) appInfoLoading = false
    })
  })

  $effect(() => {
    if (!open) return
    dialogGuardOpen()
    return () => dialogGuardClose()
  })

  async function save() {
    const nativeTitleBarChanged = draft.nativeTitleBar !== draft.originalNativeTitleBar
    try {
      await draft.saveAll()
      addToast({ type: 'success', message: $_('toast.settingsSaved') })
      if (nativeTitleBarChanged) { draft.originalNativeTitleBar = draft.nativeTitleBar; showRestartDialog = true; return }
      close()
    } catch (error) {
      console.error('Failed to save settings:', error)
      addToast({ type: 'error', message: $_('toast.failedToSaveSettings') })
    }
  }

  function close() { open = false; onClose?.() }
  function handleOpenChange(value: boolean) { open = value; if (!value) onClose?.() }

  function handleNavigationKeydown(event: KeyboardEvent, currentIndex: number) {
    let nextIndex: number | null = null
    if (event.key === 'ArrowDown') nextIndex = (currentIndex + 1) % navigation.length
    else if (event.key === 'ArrowUp') nextIndex = (currentIndex - 1 + navigation.length) % navigation.length
    else if (event.key === 'Home') nextIndex = 0
    else if (event.key === 'End') nextIndex = navigation.length - 1
    if (nextIndex === null) return

    event.preventDefault()
    event.stopPropagation()
    activePage = navigation[nextIndex].id
    const nav = (event.currentTarget as HTMLButtonElement).closest('nav')
    nav?.querySelectorAll<HTMLButtonElement>('[data-settings-page]')[nextIndex]?.focus()
  }
</script>

<Dialog.Root bind:open onOpenChange={handleOpenChange}>
  <Dialog.Content class="h-[min(680px,88vh)] max-h-[88vh] w-[min(980px,94vw)] max-w-none gap-0 overflow-hidden p-0 [&>button]:hidden" preventCloseAutoFocus onInteractOutside={(event) => event.preventDefault()}>
    <Dialog.Title class="sr-only">{$_('settings.title')}</Dialog.Title>
    <div class="grid min-h-0 flex-1 grid-cols-[210px_minmax(0,1fr)]">
      <aside class="flex min-h-0 flex-col border-r border-border bg-muted/35 px-3 py-6">
        <h1 class="mb-6 flex h-5 items-center px-2 text-lg font-semibold leading-5">{$_('settings.title')}</h1>
        <nav aria-label={$_('settings.title')}>
          <div class="space-y-1" role="tablist" aria-orientation="vertical">
            {#each navigation as item, index (item.id)}
              <button
                type="button"
                id={`settings-tab-${item.id}`}
                data-settings-page={item.id}
                role="tab"
                tabindex={activePage === item.id ? 0 : -1}
                aria-selected={activePage === item.id}
                aria-controls={`settings-panel-${item.id}`}
                class="flex h-9 w-full items-center gap-2.5 rounded-lg px-3 text-left text-sm font-medium transition-colors focus:outline-none {activePage === item.id ? 'bg-primary/12 text-primary ring-1 ring-primary/20' : 'text-muted-foreground hover:bg-background/70 hover:text-foreground'}"
                onclick={() => activePage = item.id}
                onkeydown={(event) => handleNavigationKeydown(event, index)}
              >
                <Icon icon={item.icon} class="h-[18px] w-[18px] shrink-0" /><span class="truncate">{item.label}</span>
              </button>
            {/each}
          </div>
        </nav>
        <div class="mt-auto px-2 pt-4 text-center text-xs text-muted-foreground">
          {$_('settingsAbout.version', { values: { version: appInfo?.version ?? '—' } })}
        </div>
      </aside>

      <div class="flex min-h-0 min-w-0 flex-col bg-background">
        <div
          id={`settings-panel-${activePage}`}
          role="tabpanel"
          aria-labelledby={`settings-tab-${activePage}`}
          class="min-h-0 flex-1 px-7 py-6 scrollbar-thin {activePage === 'activity' ? 'overflow-hidden' : 'overflow-y-auto'}"
        >
          {#if activePage === 'about'}<AboutTab {appInfo} loading={appInfoLoading} />
          {:else if draft.loading}
            <div class="flex h-full items-center justify-center"><Icon icon="mdi:loading" class="h-6 w-6 animate-spin text-muted-foreground" /></div>
          {:else if activePage === 'general'}<GeneralSettingsPage {draft} />
          {:else if activePage === 'appearance'}<AppearanceSettingsPage {draft} />
          {:else if activePage === 'mail'}<MailSettingsPage {draft} />
          {:else if activePage === 'accounts'}<AccountsSettingsPage />
          {:else if activePage === 'backup'}<BackupSettingsPage {draft} />
          {:else}<ActivityLogPage />{/if}
        </div>
        <footer class="flex h-16 shrink-0 items-center justify-between border-t border-border bg-background/95 px-7">
          <span class="text-xs text-muted-foreground">{draft.dirty ? $_('settings.unsavedChanges') : ''}</span>
          <div class="flex items-center gap-2">
            <Button variant="ghost" onclick={close} disabled={draft.saving}>{$_('common.cancel')}</Button>
            <Button onclick={save} disabled={draft.saving || draft.loading || !draft.dirty}>{#if draft.saving}<Icon icon="mdi:loading" class="mr-2 h-4 w-4 animate-spin" />{/if}{$_('common.save')}</Button>
          </div>
        </footer>
      </div>
    </div>
  </Dialog.Content>
</Dialog.Root>

<ConfirmDialog bind:open={showRestartDialog} title={$_('settingsGeneral.restartRequired')} description={$_('settingsGeneral.restartRequiredDescription')} confirmLabel={$_('settingsGeneral.quitNow')} cancelLabel={$_('settingsGeneral.restartLater')} onConfirm={() => QuitApp()} onCancel={() => { showRestartDialog = false; close() }} />
