// @ts-ignore - generated by Wails
import {
  GetAccentBarUnread,
  GetAlwaysLoadImages,
  GetAutomaticUpdateChecks,
  GetAutostart,
  GetBackupSettings,
  GetComposerFormat,
  GetDarkMailContent,
  GetDeveloperMode,
  GetEnhancedKeyboardNavigation,
  GetLanguage,
  GetMarkAsReadDelay,
  GetMenuBarIcon,
  GetMessageListDensity,
  GetNativeTitleBar,
  GetReadReceiptResponsePolicy,
  GetRunBackground,
  GetStartHidden,
  GetThemeMode,
  SetAccentBarUnread,
  SetAlwaysLoadImages,
  SetAutomaticUpdateChecks,
  SetAutostart,
  SetBackupSettings,
  SetComposerFormat,
  SetDarkMailContent,
  SetDeveloperMode,
  SetEnhancedKeyboardNavigation,
  SetLanguage,
  SetMarkAsReadDelay,
  SetMenuBarIcon,
  SetMessageListDensity,
  SetNativeTitleBar,
  SetReadReceiptResponsePolicy,
  SetRunBackground,
  SetStartHidden,
  SetThemeMode,
} from '../../../../wailsjs/go/app/App.js'
import {
  setAccentBarUnread as updateAccentBarUnreadStore,
  setAlwaysLoadImages as updateAlwaysLoadImagesStore,
  setComposerFormat as updateComposerFormatStore,
  setDarkMailContent as updateDarkMailContentStore,
  setDeveloperMode as updateDeveloperModeStore,
  setEnhancedKeyboardNavigation as updateEnhancedKeyboardNavigationStore,
  setLanguage as updateLanguageStore,
  setMessageListDensity as updateDensityStore,
  setThemeMode as updateThemeStore,
  type ComposerFormat,
  type MessageListDensity,
  type ThemeMode,
} from '$lib/stores/settings.svelte'
import { rememberBackupDirectory } from '$lib/utils/backup-directory-history'

export type BackupScope = 'all' | 'selected'

type Snapshot = {
  readReceiptResponsePolicy: string
  markAsReadDelaySeconds: number
  messageListDensity: string
  themeMode: string
  runBackground: boolean
  startHidden: boolean
  autostart: boolean
  language: string
  composerFormat: string
  nativeTitleBar: boolean
  alwaysLoadImages: boolean
  darkMailContent: boolean
  accentBarUnread: boolean
  menuBarIcon: boolean
  developerMode: boolean
  enhancedKeyboardNavigation: boolean
  automaticUpdateChecks: boolean
}

type BackupSnapshot = {
  directory: string
  scope: BackupScope
  selectedAccountIds: string[]
}

export class SettingsDraft {
  readReceiptResponsePolicy = $state('ask')
  markAsReadDelaySeconds = $state(1)
  messageListDensity = $state('standard')
  themeMode = $state('pop-dark')
  runBackground = $state(false)
  startHidden = $state(false)
  autostart = $state(false)
  language = $state('')
  composerFormat = $state('rich')
  nativeTitleBar = $state(false)
  alwaysLoadImages = $state(false)
  darkMailContent = $state(false)
  accentBarUnread = $state(false)
  menuBarIcon = $state(false)
  developerMode = $state(false)
  enhancedKeyboardNavigation = $state(true)
  automaticUpdateChecks = $state(true)
  backupDirectory = $state('')
  backupScope = $state<BackupScope>('all')
  backupSelectedAccountIds = $state<string[]>([])
  loading = $state(false)
  saving = $state(false)
  originalNativeTitleBar = false
  private original = $state('')
  private originalBackup = $state('')

  get dirty(): boolean {
    return this.original !== JSON.stringify(this.snapshot()) || this.backupDirty
  }

  get backupDirty(): boolean {
    return this.originalBackup !== JSON.stringify(this.backupSnapshot())
  }

  async load(): Promise<void> {
    this.loading = true
    try {
      const [policy, delayMs, density, theme, runBg, startHid, autoSt, lang, compFmt, nativeTB, alwaysImages, darkMail, accentBar, menuBar, devMode, keyboardNavigation, automaticUpdates, backup] = await Promise.all([
        GetReadReceiptResponsePolicy(), GetMarkAsReadDelay(), GetMessageListDensity(), GetThemeMode(),
        GetRunBackground(), GetStartHidden(), GetAutostart(), GetLanguage(), GetComposerFormat(),
        GetNativeTitleBar(), GetAlwaysLoadImages(), GetDarkMailContent(), GetAccentBarUnread(),
        GetMenuBarIcon(), GetDeveloperMode(), GetEnhancedKeyboardNavigation(), GetAutomaticUpdateChecks(), GetBackupSettings(),
      ])
      this.readReceiptResponsePolicy = policy
      this.markAsReadDelaySeconds = delayMs < 0 ? -1 : delayMs / 1000
      this.messageListDensity = density
      this.themeMode = theme === 'pop-dark' || theme === 'light-blue' ? theme : 'pop-dark'
      this.runBackground = Boolean(runBg)
      this.startHidden = Boolean(startHid)
      this.autostart = Boolean(autoSt)
      this.language = lang
      this.composerFormat = compFmt || 'rich'
      this.nativeTitleBar = Boolean(nativeTB)
      this.alwaysLoadImages = Boolean(alwaysImages)
      this.darkMailContent = Boolean(darkMail)
      this.accentBarUnread = Boolean(accentBar)
      this.menuBarIcon = Boolean(menuBar)
      this.developerMode = Boolean(devMode)
      this.enhancedKeyboardNavigation = keyboardNavigation ?? true
      this.automaticUpdateChecks = automaticUpdates ?? true
      this.backupDirectory = backup?.directory ?? ''
      this.backupScope = backup?.scope === 'selected' ? 'selected' : 'all'
      this.backupSelectedAccountIds = backup?.selectedAccountIds ?? []
      this.originalNativeTitleBar = this.nativeTitleBar
      this.capture()
    } finally {
      this.loading = false
    }
  }

  async saveAll(): Promise<void> {
    const snapshot = this.snapshot()
    const requestedRunBackground = snapshot.runBackground
    snapshot.runBackground = snapshot.menuBarIcon ? true : snapshot.runBackground
    const previous = this.original ? JSON.parse(this.original) as Snapshot : null
    const changed = <Key extends keyof Snapshot>(key: Key) => (
      previous === null || previous[key] !== snapshot[key]
    )
    const backupSnapshot = this.backupSnapshot()
    const backupChanged = this.originalBackup !== JSON.stringify(backupSnapshot)
    this.saving = true
    try {
      const delayMs = snapshot.markAsReadDelaySeconds < 0
        ? -1
        : Math.round(snapshot.markAsReadDelaySeconds * 1000)
      if (changed('readReceiptResponsePolicy')) await SetReadReceiptResponsePolicy(snapshot.readReceiptResponsePolicy)
      if (changed('markAsReadDelaySeconds')) await SetMarkAsReadDelay(delayMs)
      if (changed('messageListDensity')) await SetMessageListDensity(snapshot.messageListDensity)
      if (changed('themeMode')) await SetThemeMode(snapshot.themeMode)
      if (changed('runBackground')) await SetRunBackground(snapshot.runBackground)
      if (changed('startHidden')) await SetStartHidden(snapshot.startHidden)
      if (changed('autostart')) await SetAutostart(snapshot.autostart)
      if (changed('language') && snapshot.language) await SetLanguage(snapshot.language)
      if (changed('composerFormat')) await SetComposerFormat(snapshot.composerFormat)
      if (changed('nativeTitleBar')) await SetNativeTitleBar(snapshot.nativeTitleBar)
      if (changed('alwaysLoadImages')) await SetAlwaysLoadImages(snapshot.alwaysLoadImages)
      if (changed('darkMailContent')) await SetDarkMailContent(snapshot.darkMailContent)
      if (changed('accentBarUnread')) await SetAccentBarUnread(snapshot.accentBarUnread)
      if (changed('menuBarIcon')) await SetMenuBarIcon(snapshot.menuBarIcon)
      if (changed('developerMode')) await SetDeveloperMode(snapshot.developerMode)
      if (changed('enhancedKeyboardNavigation')) await SetEnhancedKeyboardNavigation(snapshot.enhancedKeyboardNavigation)
      if (changed('automaticUpdateChecks')) await SetAutomaticUpdateChecks(snapshot.automaticUpdateChecks)
      if (backupChanged) await this.persistBackupSnapshot(backupSnapshot)

      if (
        this.runBackground === requestedRunBackground
        && this.menuBarIcon === snapshot.menuBarIcon
      ) this.runBackground = snapshot.runBackground
      if (changed('messageListDensity')) updateDensityStore(snapshot.messageListDensity as MessageListDensity)
      if (changed('themeMode')) updateThemeStore(snapshot.themeMode as ThemeMode)
      if (changed('language') && snapshot.language) updateLanguageStore(snapshot.language)
      if (changed('composerFormat')) updateComposerFormatStore(snapshot.composerFormat as ComposerFormat)
      if (changed('alwaysLoadImages')) updateAlwaysLoadImagesStore(snapshot.alwaysLoadImages)
      if (changed('darkMailContent')) updateDarkMailContentStore(snapshot.darkMailContent)
      if (changed('accentBarUnread')) updateAccentBarUnreadStore(snapshot.accentBarUnread)
      if (changed('developerMode')) updateDeveloperModeStore(snapshot.developerMode)
      if (changed('enhancedKeyboardNavigation')) updateEnhancedKeyboardNavigationStore(snapshot.enhancedKeyboardNavigation)
      this.original = JSON.stringify(snapshot)
      if (backupChanged) this.originalBackup = JSON.stringify(backupSnapshot)
    } finally {
      this.saving = false
    }
  }

  async saveBackup(): Promise<void> {
    const snapshot = this.backupSnapshot()
    await this.persistBackupSnapshot(snapshot)
    this.originalBackup = JSON.stringify(snapshot)
  }

  private async persistBackupSnapshot(snapshot: BackupSnapshot): Promise<void> {
    await SetBackupSettings(snapshot)
    if (snapshot.directory) rememberBackupDirectory(snapshot.directory)
  }

  private capture(): void {
    this.original = JSON.stringify(this.snapshot())
    this.originalBackup = JSON.stringify(this.backupSnapshot())
  }

  private backupSnapshot(): BackupSnapshot {
    return {
      directory: this.backupDirectory.trim(),
      scope: this.backupScope,
      selectedAccountIds: [...this.backupSelectedAccountIds].sort(),
    }
  }

  private snapshot(): Snapshot {
    return {
      readReceiptResponsePolicy: this.readReceiptResponsePolicy,
      markAsReadDelaySeconds: this.markAsReadDelaySeconds,
      messageListDensity: this.messageListDensity,
      themeMode: this.themeMode,
      runBackground: this.runBackground,
      startHidden: this.startHidden,
      autostart: this.autostart,
      language: this.language,
      composerFormat: this.composerFormat,
      nativeTitleBar: this.nativeTitleBar,
      alwaysLoadImages: this.alwaysLoadImages,
      darkMailContent: this.darkMailContent,
      accentBarUnread: this.accentBarUnread,
      menuBarIcon: this.menuBarIcon,
      developerMode: this.developerMode,
      enhancedKeyboardNavigation: this.enhancedKeyboardNavigation,
      automaticUpdateChecks: this.automaticUpdateChecks,
    }
  }
}
