// Configure Iconify to work offline with bundled icon data.
//
// Instead of bundling the FULL icon sets (~16 MB — mdi/lucide/heroicons/logos/
// simple-icons in their entirety), we bundle ONLY the icons actually referenced
// in the source. The subset is generated by scripts/gen-icons.cjs (run via
// `npm run gen-icons`, also wired into the build) into iconify-subset.json.
//
// To add a new icon: reference it in markup, then run
// `npm run gen-icons` to refresh the subset.
import { addCollection, type IconifyJSON } from '@iconify/svelte'
import subset from './iconify-subset.json'

for (const collection of Object.values(subset as Record<string, IconifyJSON>)) {
  addCollection(collection)
}
